### ISSUE TITLE
mgc file creation during acoustic step

### ISSUE THREAD

**Issue by SirPounce** [CSTR-Edinburgh/merlin#143]
I am currently working on building a swedish voice using rich label format files generated by hmm. I have managed to get the duration model to run through without complaints but when starting the acoustic step i get this:

2017-05-03 15:37:07,146 INFO      acoustic_comp: processing file    1 of   60 : /data/joniva/build_swedish_voice/experiments/nst_swe_dnn/acoustic_model/data/nn_mgc_lf0_vuv_bap_187/sw_all_mf_01_0001.pcm.cmp
Traceback (most recent call last):
  File "/data/joniva/software/merlin//src/run_merlin.py", line 1175, in <module>
    main_function(cfg)
  File "/data/joniva/software/merlin//src/run_merlin.py", line 693, in main_function
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, cfg.in_dimension_dict, cfg.out_dimension_dict)
  File "/data/joniva/software/merlin/src/frontend/acoustic_base.py", line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_dimension_dict)
  File "/data/joniva/software/merlin/src/frontend/acoustic_composition.py", line 126, in prepare_data
    features, frame_number = io_funcs.load_binary_file_frame(in_file_name, in_feature_dim)
  File "/data/joniva/software/merlin/src/io_funcs/binary_io.py", line 64, in load_binary_file_frame
    fid_lab = open(file_name, 'rb')
IOError: [Errno 2] No such file or directory: '/data/joniva/build_swedish_voice/experiments/nst_swe_dnn/acoustic_model/data/mgc/sw_all_mf_01_0001.pcm.mgc'

When i look around i find no acoustic_model/data/mgc/ folder or mgc-files generated. And no files in the folder /acoustic_model/data/nn_mgc_lf0_vuv_bap_187/  where the script is also looking for mgc-files.

I'm wondering if there is a simple answer to how these files are created and what files/folders are missing in order for them to be generated.

*Edit I found the vocoder generation script included. Sorry to waste your time.

**Comment by dreamk73** [comment]
Did you run the World script to extract acoustic features? It creates the mgc folder and files. 

Esther

**Comment by SirPounce** [comment]
Yes it worked like a charm. Thanks the issue is resolved.
