### ISSUE TITLE
demo runtime error

### ISSUE THREAD

**Issue by willian56** [CSTR-Edinburgh/merlin#157]
I run the demo with this error message,is there anyone helpful?honestly thankful.

2017-06-03 09:47:06,740 CRITICAL       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/home/willian/merlin/src/run_merlin.py", line 1175, in <module>
    main_function(cfg)
  File "/home/willian/merlin/src/run_merlin.py", line 838, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector)
  File "/home/willian/merlin/src/run_merlin.py", line 300, in train_DNN
    shared_valid_set_xy, temp_valid_set_x, temp_valid_set_y = valid_data_reader.load_one_partition()
  File "/home/willian/merlin/src/utils/providers.py", line 179, in load_one_partition
    shared_set_xy, temp_set_x, temp_set_y = self.load_next_partition()
  File "/home/willian/merlin/src/utils/providers.py", line 299, in load_next_partition
    temp_set_x = numpy.empty((self.buffer_size, self.n_ins))
MemoryError

**Comment by ronanki** [comment]
Decrease the buffer size in conf files or you can change the same in "utils/providers.py"

**Comment by willian56** [comment]
thx，I'll hava a try

**Comment by beike12138** [comment]
Hello
I am a beginner and I have encountered the same problem. How did you solve it? How to reduce the buffer size in the conf file?

**Comment by willian56** [comment]
You can reduce the number of "batch_size" in your configuration file which name ends up with ".conf" in your  "conf/" directory. Hope it helpful for you.

**Comment by willian56** [comment]
@beike12138 You can reduce the number of "batch_size" in your configuration file which name ends up with ".conf" in your "conf/" directory. Hope it helpful for you.

**Comment by beike12138** [comment]
Thank you for your guidance, this is very helpful to me.
