### ISSUE TITLE
Error in training acoustic model for my own wav files

### ISSUE THREAD

**Issue by reiinakano** [CSTR-Edinburgh/merlin#173]
While training my acoustic model with:
`./scripts/submit.sh ${MerlinDir}/src/run_merlin.py conf/acoustic_${Voice}.conf`
in `run_merlin.sh`, I encountered this error.

```
2017-06-22 14:15:52,141 INFO           main    : saved 425 vectors to /home/ubuntu/pynb/TFplay/merlin/egs/build_your_own_voice/s1/experiments/my_voice/acoustic_model/data/label_norm_HTS_425.dat
2017-06-22 14:15:52,141 INFO           main    : creating acoustic (output) features
2017-06-22 14:15:52,142 INFO      acoustic_comp: processing file    1 of  131 : /home/ubuntu/pynb/TFplay/merlin/egs/build_your_own_voice/s1/experiments/my_voice/acoustic_model/data/nn_mgc_lf0_vuv_bap_199/myvoice_0000.cmp
Traceback (most recent call last):
  File "/home/ubuntu/pynb/TFplay/merlin/src/run_merlin.py", line 1172, in <module>
    main_function(cfg)
  File "/home/ubuntu/pynb/TFplay/merlin/src/run_merlin.py", line 693, in main_function
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, cfg.in_dimension_dict, cfg.out_dimension_dict)
  File "/home/ubuntu/pynb/TFplay/merlin/src/frontend/acoustic_base.py", line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_dimension_dict)
  File "/home/ubuntu/pynb/TFplay/merlin/src/frontend/acoustic_composition.py", line 157, in prepare_data
    delta_features = self.compute_dynamic_matrix(features, self.delta_win, frame_number, in_feature_dim)
  File "/home/ubuntu/pynb/TFplay/merlin/src/frontend/acoustic_base.py", line 193, in compute_dynamic_matrix
    dynamic_matrix[:, dim:dim+1] = self.compute_dynamic_vector(data_matrix[:, dim], dynamic_win, frame_number)
  File "/home/ubuntu/pynb/TFplay/merlin/src/frontend/acoustic_base.py", line 178, in compute_dynamic_vector
    temp_vector[w, 0] = vector[0, 0]
IndexError: index 0 is out of bounds for axis 0 with size 0
Lock freed

```

Any ideas what may have caused this?

**Comment by hwong39** [comment]
the order of acoustic parameters does not match the system. you mast make your mgc 60,bap 1,lf0 1,if you use WORLD. .......you are supportsd to try      merlin-master/misc/scripts/vocoder/world/extract_features_for_merlin.sh
