### ISSUE TITLE
Can we only use the static acoustic features??

### ISSUE THREAD

**Issue by DabiaoMa** [CSTR-Edinburgh/merlin#183]
Since the dataset I am using is a small one, I would like to only use the static acoustic features( static MGC, lf0, bap and vuv).

Would you please tell me which configure file I need to modify to achieve this purpose?  Thanks.

**Comment by ronanki** [comment]
Sure, you can. 

Edit the Outputs section of the acoustic config files as shown below:
[Outputs]
# dX should be 3 times X for dynamic features
mgc: 60
dmgc: 60
bap: 1
dbap: 1
lf0: 1
dlf0: 1

**Comment by DabiaoMa** [comment]
Thanks a lot!

**Comment by DabiaoMa** [comment]
@ronanki,

While I edited the acoustic config and test_synth config as you told me,  It goes well when trainning. But when I start to generate new wavs, errors appear :

2017-07-12 14:42:40,743 DEBUG   param_generation:  feature: mgc
2017-07-12 14:42:40,743 DEBUG   param_generation: starting MLParameterGeneration.generation
2017-07-12 14:42:40,746 DEBUG   param_generation:  feature dimensions: 440 by 20
2017-07-12 14:42:40,747 DEBUG   param_generation:  wrote to file /home/madabiao/workspace/merlin_5000_2/merlin-master_succeed_500/egs/005_hdl_test/s1/experiments/ht-500-data/test_synthesis/wav/uzoo_cn_ht5000_hdl_361491.mgc
2017-07-12 14:42:40,747 DEBUG   param_generation:  feature: lf0
2017-07-12 14:42:40,747 DEBUG   param_generation: starting MLParameterGeneration.generation
2017-07-12 14:42:40,747 DEBUG   param_generation:  feature dimensions: 440 by 0
Traceback (most recent call last):
  File "/home/madabiao/workspace/merlin_5000_2/merlin-master_succeed_500/src/run_merlin.py", line 1163, in <module>
    main_function(cfg)
  File "/home/madabiao/workspace/merlin_5000_2/merlin-master_succeed_500/src/run_merlin.py", line 931, in main_function
    generator.acoustic_decomposition(gen_file_list, cfg.cmp_dim, cfg.out_dimension_dict, cfg.file_extension_dict, var_file_dict, do_MLPG=cfg.do_MLPG, cfg=cfg)    
  File "/home/madabiao/workspace/merlin_5000_2/merlin-master_succeed_500/src/frontend/parameter_generation.py", line 174, in acoustic_decomposition
    gen_features[i, 0] = self.inf_float
IndexError: index 0 is out of bounds for axis 1 with size 0

**Comment by DabiaoMa** [comment]
Thanks! It works.
