### ISSUE TITLE
demo_error —— wav_generation

### ISSUE THREAD

**Issue by willian56** [CSTR-Edinburgh/merlin#185]
hi, guy.
I'm running merlin demo, but there occurr a error, I need some help, could you please give me some advice.
It is normal for "param_generation", but when it comes to "wav_generation", the error occurs, the error message   is listed below:
Traceback (most recent call last):
  File "/home/willing/merlin/src/run_merlin.py", line 1132, in <module>
    main_function(cfg)
  File "/home/willing/merlin/src/run_merlin.py", line 918, in main_function
    generate_wav(gen_dir, gen_file_id_list, cfg)     # generated speech
  File "/home/willing/merlin/src/utils/generate.py", line 200, in generate_wav
    .format(line=line, x2x=SPTK['X2X'], weight=os.path.join(gen_dir, 'weight')))
  File "/home/willing/merlin/src/utils/generate.py", line 83, in run_process
    close_fds=True, env=os.environ)
  File "/home/willing/anaconda2/envs/merlin/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/willing/anaconda2/envs/merlin/lib/python2.7/subprocess.py", line 916, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by willian56** [comment]
I finally find a way to solve this problem, there is a link for reference. Hope to be of help to you
http://bryanmarty.com/2012/01/14/forking-jvm/

**Comment by willian56** [comment]
I finally find a solution to this question, there is a link for reference, hope to be of help for others.
http://bryanmarty.com/2012/01/14/forking-jvm/
