### ISSUE TITLE
Bug With Voice conversion

### ISSUE THREAD

**Issue by rhajit1001** [CSTR-Edinburgh/merlin#202]
When trying to run "05_train_acoustic_model.sh" I get:

```
Traceback (most recent call last):
  File "/home/eliezeg/ron/merlin_new/merlin/src/run_merlin.py", line 1158, in <module>
    main_function(cfg)
  File "/home/eliezeg/ron/merlin_new/merlin/src/run_merlin.py", line 534, in main_function
    if cfg.VoiceConversion:
AttributeError: 'configuration' object has no attribute 'VoiceConversion'
```

How can I fix this?

**Comment by ronanki** [comment]
We forgot to update the configuration file -- it's fixed now. Please use `git pull` to pull the latest commit.

**Comment by rhajit1001** [comment]
Thanks a lot
