### ISSUE TITLE
Error in 05_train_duration_model.sh and 06_train_acoustic_model.sh

### ISSUE THREAD

**Issue by Rododendron82** [CSTR-Edinburgh/merlin#203]
When I tried to build my own voice in the 5th and 6th steps I have this error:
`Traceback (most recent call last):
  File "/home/tarik/merlin-master/src/run_merlin.py", line 1158, in <module>
    main_function(cfg)
  File "/home/tarik/merlin-master/src/run_merlin.py", line 534, in main_function
    if cfg.VoiceConversion:
AttributeError: 'configuration' object has no attribute 'VoiceConversion'`

**Comment by rhajit1001** [comment]
When did you pull the project last time? IIRC they fixed it a few hours ago.

**Comment by Rododendron82** [comment]
I have downloaded a few hours ago.
Ok. I try a new version downloaded a few minuts ago.
And there are new error:
`2017-08-03 16:56:24,697 CRITICALListDataProvider: first list is empty
2017-08-03 16:56:24,697 CRITICAL       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/home/tarik/merlin-master/src/run_merlin.py", line 1158, in <module>
    main_function(cfg)
  File "/home/tarik/merlin-master/src/run_merlin.py", line 817, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector)
  File "/home/tarik/merlin-master/src/run_merlin.py", line 241, in train_DNN
    n_ins = n_ins, n_outs = n_outs, buffer_size = buffer_size, sequential = sequential_training, shuffle = False)
  File "/home/tarik/merlin-master/src/utils/providers.py", line 88, in __init__
    assert len(x_file_list) > 0
AssertionError`

**Comment by ronanki** [comment]
Did you change train, valid, test file number in `conf/global_settings.cfg` as per your data?

**Comment by Rododendron82** [comment]
> Did you change train, valid, test file number in conf/global_settings.cfg as per your data?
No.
Could you explain what values (train, valid, test) I have to enter?

**Comment by ronanki** [comment]
If you have a total of 1000 files, use 90% for training, and 5% each for valid, test. i.e., 900, 50, 50. 
If you have a total of 500 files, use 450, 25, 25 for train, valid and test respectively.

**Comment by Rododendron82** [comment]
I have 500 wav and 500 txt files, but in label_state_align generated 250 files.
So, I change global_settings.cfg:
`Train=200
Valid=15
Test=10`
Script 05_train_duration_model.sh terminates without critical errors, but it have validation errors like this:
`2017-08-04 10:35:32,585 DEBUG    main.train_DNN: calculating validation loss
2017-08-04 10:35:32,823 INFO     main.train_DNN: epoch 1, validation error 5.841296, train error 4.714705  time spent 6.14`
After that, script 06_train_acoustic_model.sh returns critical errors:
`IOError: [Errno 2] No such file or directory: '/home/tarik/merlin-master/egs/build_your_own_voice/s1/experiments/239/acoustic_model/data/mgc/p225_001.mgc'`
[4-5-steps-log.txt](https://github.com/CSTR-Edinburgh/merlin/files/1199613/4-5-steps-log.txt)
