### ISSUE TITLE
Error during step 2 of "02_prepare_labels.sh" 

### ISSUE THREAD

**Issue by HandsomeDevilv112** [CSTR-Edinburgh/merlin#223]
While trying to make my own voice, I've managed to complete step 1 of "02_prepare_labels.sh" (after properly installing the other tools)
But then during step 2, it fails automatically, and my sincere apologies, but I'm pretty out of my element with the error messaging.

Labels are ready in: /home/al/merlin/egs/build_your_own_voice/s1/label_no_align !!
Step 2: forced-alignment using HTK tools...
---preparing enverionment
---checking data
---extracting features
Traceback (most recent call last):
  File "forced_alignment.py", line 379, in <module>
    aligner.prepare_training(file_id_list_name, wav_dir, lab_dir, work_dir, multiple_speaker)
  File "forced_alignment.py", line 253, in prepare_training
    self._HCopy()
  File "forced_alignment.py", line 190, in _HCopy
    check_call([HCopy, '-C', self.cfg, '-S', self.copy_scp])
  File "/usr/lib/python2.7/subprocess.py", line 536, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 523, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by seblemaguer** [comment]
Hello,

he seems to not find a file. are you sure HCopy (the command) is available: HTK/HTS is installed ?

**Comment by HandsomeDevilv112** [comment]
Heya new friend, I ran the compile_htk.sh in merlin/tools, but it's very possible that I made an error during the process. I'll try running that again to see if it'll give me a different result

**Comment by HandsomeDevilv112** [comment]
it sure looks like it installed correctly at the right location, but it has not successfully been able to "make the donuts" 
How would you install htk?

**Comment by ronanki** [comment]
If you are facing troubles with HTK, then try other alternative:

- change the `Labels=state_align` to `Labels=phone_align` in `conf/global_settings.cfg`
- run both steps of `02_prepare_labels.sh`

**Comment by HandsomeDevilv112** [comment]
I must be doing something wrong. 
Changing state_align to phone_align in global settings and running 02_prepare_labels.sh, I'm encountering the exact same error with references to forced_alignment.py from state_align.
Just trying to run run_aligner.sh in phone_align runs the slt demo, and appears very tied to the demo. 
My apologies, but I'm feeling rather clueless

**Comment by r9y9** [comment]
> OSError: [Errno 2] No such file or directory

I believe this is because `HCopy` cannot be found by the forced_alignment.py.  Did you check that paths in https://github.com/CSTR-Edinburgh/merlin/blob/8ff864e22f6c2561b4877193c0145feb29471442/misc/scripts/alignment/state_align/forced_alignment.py#L19-L24 are correct?

**Comment by HandsomeDevilv112** [comment]
I hadn't, but it looks like the place to be... Right?
`HTKDIR = "/home/al/merlin/tools/htk"
HCompV = os.path.join(HTKDIR, 'HCompV')
HCopy  = os.path.join(HTKDIR, 'HCopy' )
HERest = os.path.join(HTKDIR, 'HERest')
HHEd   = os.path.join(HTKDIR, 'HHEd'  )
HVite  = os.path.join(HTKDIR, 'HVite' )`

**Comment by HandsomeDevilv112** [comment]
doing further research, I'm back to HTK is not properly installed. I found a reference saying "Hvite -V" should produce basic version information. Mine says "no command found". I'm not sure where my installation of HTK (through "tools/compile_htk.sh") failed, as it certainly didn't produce a "failed to build" message.

**Comment by r9y9** [comment]
https://github.com/CSTR-Edinburgh/merlin/blob/8ff864e22f6c2561b4877193c0145feb29471442/tools/compile_htk.sh#L52

Ah, I may find the problem. Can you try `HTKDIR = "/home/al/merlin/tools/bin/htk"` instead of `HTKDIR = "/home/al/merlin/tools/htk"`? Also, please make sure that you have htk binaries inside `HTKDIR`.

**Comment by HandsomeDevilv112** [comment]
New errors = Progress! 
Question: I don't see a folder labeled binaries, do you just mean the contents of the htk folder?

python forced_alignment.py
---preparing enverionment
---checking data
---extracting features
Sat Sep  2 03:34:15 2017
---feature_normalisation
Sat Sep  2 03:34:36 2017
---making proto
Sat Sep  2 03:34:43 2017
---training HMM models
  ERROR [+7390]  StepAlpha: Alpha prune failed sq(3541) > qHi(3540) at time 81482
 FATAL ERROR - Terminating program /home/al/merlin/tools/bin/htk/HERest
Traceback (most recent call last):
  File "forced_alignment.py", line 381, in <module>
    aligner.train_hmm(7, 32)
  File "forced_alignment.py", line 285, in train_hmm
    stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/al/merlin/tools/bin/htk/HERest', '-C', '/home/al/merlin/egs/build_your_own_voice/s1/labels/config/cfg', '-S', '/home/al/merlin/egs/build_your_own_voice/s1/labels/config/train.scp', '-I', '/home/al/merlin/egs/build_your_own_voice/s1/labels/config/mono_phone.mlf', '-M', '/home/al/merlin/egs/build_your_own_voice/s1/labels/model/hmm_mix_1_iter_1', '-H', '/home/al/merlin/egs/build_your_own_voice/s1/labels/model/hmm0/macros', '-H', '/home/al/merlin/egs/build_your_own_voice/s1/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/home/al/merlin/egs/build_your_own_voice/s1/labels/mono_phone.list']' returned non-zero exit status 222

**Comment by r9y9** [comment]
I meant check that htk binarires (i.e., `HCompV`, `HCopy`) actually exist.

**Comment by HandsomeDevilv112** [comment]
o~h. Okay. Thank you. Yes. merlin/tools/bin/htk has 16 items. All of them are HSomething.

**Comment by HandsomeDevilv112** [comment]
I'm going to go ahead and close this, as the problem was htk pathing related. I will enter a new report if I encounter a new problem. Thanks!

**Comment by r9y9** [comment]
The original problem hasn't been solved in Merlin. Probably needs fix for `build_your_own_voice`. I think we should keep the issue open.

**Comment by HandsomeDevilv112** [comment]
reopening per above

**Comment by abhigarg** [comment]
I got the ERROR [+2019]  HCompV: Training data file name expected  
while running "02_prepare_labels.sh" and I have checked all the paths seems correct.   The error is thrown at `check_call([HCompV, '-f', F, '-C', self.cfg,
                              '-S', self.train_scp,
                              '-M', self.cur_dir, self.proto])`
One thing I noticed is that if I give my own path for labels_dir then it throws an error while executing "forced_alignment.py" that labels path not found because it messes up the path by adding path of merlin to the path I have already provided.

**Comment by abhigarg** [comment]
I copied the wave and text folders to the /merlin/egs/build_your_own_voice/s1/ directory and that seems to have resolved the issue

**Comment by abhigarg** [comment]
I also ended up with same error as @HandsomeDevilv112   
ERROR [+7390]  StepAlpha: Alpha prune failed sq(9) > qHi(8) at time 60116
 FATAL ERROR - Terminating program ../merlin/tools/bin/htk/HERest

**Comment by abhigarg** [comment]
Found some hints to resolve this issue:  
https://firojalam.wordpress.com/2014/01/23/herest-error-7390-stepalpha-alpha-prune-failed/
https://stackoverflow.com/questions/5463645/htk-herest-issue

**Comment by HandsomeDevilv112** [comment]
My apologies for not following up.
Yeah, I got past the alpha prune error by turning up the targetrate as suggested by the firojalam wordpress. I forget if I doubled the default rate, or added an extra zero.
I've kinda experienced an unrelated issue that resulted in me having to reformat, so I don't have the information handy, but if memory serves, the next issue I faced was that the files needed to be in mono configuration. This can be solved easily with audacity.

**Comment by abhigarg** [comment]
I am stuck at hmm training step since more than half a day now. Any ideas
how can I get the status of the training like usually some kind of error
rates or accuracy values. Its not showing me anything to know the status of
the training.

**Comment by HandsomeDevilv112** [comment]
I remember having a similar thought. I forget the last message printed, but mine eventually finished somewhere in the "half a day" period.
I do agree that some additional messaging wouldn't go unappreciated.

**Comment by ZofiaMalisz** [comment]
I encountered an identical error as the original poster while trying to build a new voice. 

I checked the paths (forced_alignment.py, global_settings.cfg), checked the installation of htk (provided compile_htk.sh was not successful, I copied a functional installation into tools/htk), to no avail. 

Does it need a fix in Merlin or does anybody have a hint what I could try? Thanks.

**Comment by HandsomeDevilv112** [comment]
just to ask, did you do the whole login/password dance to install HTK? It's a bit of a pain.

**Comment by raghdr** [comment]
Just wanted to note that I got stuck at hmm training step too. No progress after the log message:
Step 2: forced-alignment using HTK tools...
but the process was running for more than a day.

I am using Python 2.7 and the subprocess.check_call documentation says "Do not use stdout=PIPE or stderr=PIPE with this function as that can deadlock based on the child process output volume". But the train_hmm() function in forced_alignment.py runs HERest using check_call with stdout=PIPE
It progressed for me after explicitly opening a file and changing stdout=stdoutlog.

**Comment by Sangramsingkayte** [comment]
Step 2: 
Preparing labels...
mkdir: cmu_us_IIIT: File exists
Copying labels to duration and acoustic data directories...
sed: 1: "experiments/IIIT/durati ...": invalid command code e
sed: 1: "experiments/IIIT/acoust ...": invalid command code e
done...!

**Comment by raghdr** [comment]
@Sangramsingkayte 
1) Are the labels correctly created in your $lab_dir? I guess not since your log does not print "You should have your labels ready in: <>". Maybe you could  try deleting cmu_us_IIIT and retry?

(These label filenames are written to $FileIDList and the sed command just removes the .lab extension, you could go through the 02_prepare_labels and run_aligner scripts line by line)

2) If (1) is not the case, are you running on Mac OS? It has a lot of idiosyncrasies when compared to Unix/Linux (https://markhneedham.com/blog/2011/01/14/sed-sed-1-invalid-command-code-r-on-mac-os-x/)

**Comment by Sangramsingkayte** [comment]
DrSangramsings-MacBook-Air:s1 sangramsing$ bash ./02_prepare_labels.sh ./database/wav ./database/txt.txt ./database/labels 
Step 2: 
Preparing labels...
mkdir: cmu_us_sing_iiit: File exists
Copying labels to duration and acoustic data directories...
sed: 1: "experiments/sing_iiit/d ...": invalid command code e
sed: 1: "experiments/sing_iiit/a ...": invalid command code e
done...!

**Comment by mirfan899** [comment]
got the same issue related to hmm training. Here is the output of error
```shell
95.lab
96.lab
97.lab
98.lab
99.lab
forced-alignment using HTK tools...
HTK step 1 success
HTK step 2 success
HTK step 3 success
---preparing enverionment
---checking data
---extracting features
Fri Jun  7 11:16:18 2019
---feature_normalisation
Fri Jun  7 11:16:25 2019
---making proto
Fri Jun  7 11:16:25 2019
---training HMM models
Traceback (most recent call last):
  File "/home/virtuoso_irfan/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 381, in <module>
    aligner.train_hmm(7, 32)
  File "/home/virtuoso_irfan/merlin/misc/scripts/alignment/state_align/forced_alignment.py", line 285, in train_hmm
    stdout=PIPE)
  File "/root/anaconda3/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/home/virtuoso_irfan/merlin/tools/bin/htk/HERest', '-C', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/cfg', '-S', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/train.scp', '-I', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/mono_phone.mlf', '-M', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm_mix_1_iter_1', '-H', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/macros', '-H', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/mono_phone.list']' returned non-zero exit status -11
Force-alignment unsucessful!! Please check /home/virtuoso_irfan/merlin/misc/scripts/alignment/state_align/forced_alignment.py
Copying labels to duration and acoustic data directories...
done...!
```

**Comment by RasmusD** [comment]
Hi @mirfan899 
If you try and run forced_alignment.py by itself you can try and debug from the output of that. It'll give you more helpful errors.

**Comment by mirfan899** [comment]
I believe adding new voice is not clear. There are missing links to build the custom voice. For example no information about `questions set`, `phoneme_map.dict`. No clear errors found when I tried to run `forced_alignment.py`. It just shows 
```shell
subprocess.CalledProcessError: Command '['/home/virtuoso_irfan/merlin/tools/bin/htk/HERest', '-C', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/cfg', '-S', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/train.scp', '-I', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/mono_phone.mlf', '-M', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm_mix_1_iter_1', '-H', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/macros', '-H', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/hmmdefs', '-t', '250.0', '150.0', '2000.0', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/mono_phone.list']' returned non-zero exit status -11
Force-alignment unsucessful!! Please check /home/virtuoso_irfan/merlin/misc/scripts/alignment/state_align/forced_alignment.py
```

**Comment by RasmusD** [comment]
Try running the command that the python program is running (HERest) and see the errors the

**Comment by mirfan899** [comment]
So here is what I get when I try to run `check_call` on `HERest`
```shell
WARNING [-7325]  LoadUtterance: No labels in file /home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/mfc/10.lab in /home/virtuoso_irfan/merlin/tools/bin/htk/HERest
```
It looks like `check_call` using HERest looking into wrong directory for labels file.

`check_call` in `train_hmm`
```python
check_call([HERest, '-C', self.cfg, '-S', self.train_scp,
                            '-I', self.phoneme_mlf,
                            '-M', next_dir,
                            '-H', os.path.join(self.cur_dir, MACROS),
                            '-H', os.path.join(self.cur_dir, HMMDEFS),
                            '-t'] + PRUNING + [self.phonemes],
                           stdout=PIPE)
```
Here are the paths which are set for running this function
```shell
/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/cfg
/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/train.scp
/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/config/mono_phone.mlf
/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm_mix_1_iter_1
/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/macros
/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/model/hmm0/hmmdefs
['250.0', '150.0', '2000.0', '/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/mono_phone.list']
```

**Comment by mirfan899** [comment]
I think it's a language issue. I'm using `Urdu` and it causes issues with underlying scripts for building labels as utterances generated by Merling are in `ascii` but `Urdu` requires `unicode`.

**Comment by RasmusD** [comment]
It sounds unlikely to be a unicode issue. Unless you use unicode in the labels you generate?

Even then, the error you report is HEREst looking in the wrong directory? Why not fix that?

**Comment by mirfan899** [comment]
After looking hard into the issue, did not get anything good. From this warning message
```shell
WARNING [-7325]  LoadUtterance: No labels in file /home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/mfc/10.lab in /home/virtuoso_irfan/merlin/tools/bin/htk/HERest
```
HERest is looking for `10.lab` file but mfc directory only contains `*.mfc` files. Further investgating the issue, I got `config/train.scp` script file used in HERest and contains the absolute addresses of `mfc` files.
I've also looked for error on Google and here are the links that provide some info
https://www.xuebuyuan.com/2063956.html
https://anggarrgoon.wordpress.com/tag/htk/
http://electroblaze.blogspot.com/2013/03/understanding-htk-error-messages.html

**Comment by seblemaguer** [comment]
I think something might be off in your mlf file: can you check its syntax and the existence of the directory(ies) indicated inside

**Comment by mirfan899** [comment]
here is the content of mlf file
```text
#!MLF!#
"*/*.lab" -> "/home/virtuoso_irfan/merlin/egs/build_your_own_voice/s1/database/labels/mono_no_align"
```

**Comment by pilarOG** [comment]
Hi, I got the same problem. You have to check if you have all the labels inside the database/labels/mono_no_align, then check if the file that is given you the error 10.lab has anything inside. In my case, this was the problem as the file was empty. I just took it out from the file_id_list of the forced alignment. Then the alignment ran ok. Hope that helps!

**Comment by rrmhearts** [comment]
Just sharing my experience with this error from 2023. It occurred because of a different error higher up in the log output, I believe the error was in the `02_prepare_labels.sh` script.  Anyways, one of the wav files was not processing correctly for some reason and gave a segfault,

```
arctic_a0034
/merlin/tools/festival/examples/dumpfeats -eval /merlin/misc/scripts/frontend/festival_utt_to_lab/extra_feats.scm -relation Segment -feats /merlin/misc/scripts/frontend/festival_utt_to_lab/label.feats -output database/lab/prompt-lab/tmp database/lab/prompt-utt/arctic_a0034.utt
/merlin/misc/scripts/frontend/festival_utt_to_lab/make_labels: line 22: 11341 Segmentation fault      $dumpfeats -eval $scripts/extra_feats.scm -relation Segment -feats $scripts/label.feats -output $labels/tmp $utt
```

After deleting `arctic_a0034.wav` and the associated text for it, everything started working great. I do not know what about this file caused cascading errors. The HERest error (mentioned above) occurred after and because of this initial error.

It worked fine beforehand with `phone_align` but did not work with `state_align` until I deleted the misbehaving file.
