### ISSUE TITLE
Voice convertion -> 3 step -> IndexError

### ISSUE THREAD

**Issue by Rododendron82** [CSTR-Edinburgh/merlin#232]
I have error in script 03_align_src_with_target.sh:
`--- DTW alignment started ---
1
110
121
132
143
154
165
176
187
Traceback (most recent call last):
  File "/home/tarik/merlin-master/misc/scripts/voice_conversion/dtw_aligner_festvox.py", line 158, in <module>
    pool.map(process, mgc_files)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IndexError: index 437 is out of bounds for axis 0 with size 437
Copying features to acoustic data directory...
preparing file list...
done...!
`
What can I do?

**Comment by AhensNamar** [comment]
I have a similar error. Were you able to solve it?

**Comment by Rododendron82** [comment]
I haven't solved this issue.

**Comment by ronanki** [comment]
As an alternative, try replacing `dtw_aligner_festvox.py` with `dtw_aligner.py` at [line number 60](https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/voice_conversion/s1/03_align_src_with_target.sh#L60).
