### ISSUE TITLE
FileNotFound error when using Keras

### ISSUE THREAD

**Issue by AhensNamar** [CSTR-Edinburgh/merlin#257]
I am using keras to train with switch_to_keras as True

I get this error when training the source to target
What am I missing? I cant see .lab files anywhere.

Traceback (most recent call last):
  File "//home/aholab/merlin/src/run_merlin.py", line 1226, in <module>
    main_function(cfg)
  File "//home/aholab/merlin/src/run_merlin.py", line 813, in main_function
    keras_instance.train_keras_model()
  File "/home/aholab/merlin/src/run_keras_with_merlin_io.py", line 184, in train_keras_model
    self.inp_dim, self.out_dim, sequential_training=self.sequential_training)
  File "/home/aholab/merlin/src/keras_lib/data_utils.py", line 76, in read_data_from_file_list
    inp_features, inp_frame_number = io_funcs.load_binary_file_frame(inp_file_name, inp_dim)
  File "/home/aholab/merlin/src/io_funcs/binary_io.py", line 64, in load_binary_file_frame
    fid_lab = open(file_name, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '//home/aholab/merlin/egs/voice_conversion/s1/experiments/bdl2slt/acoustic_model/inter_module/nn_no_silence_lab_norm_187/arctic_a0001.lab'

**Comment by ronanki** [comment]
The extension recipes like `voice_conversion` and `speaker_adaptation` were never tested either in Keras or Tensorflow. So, they may not work unless you debug.
