### ISSUE TITLE
alternative vocoders?

### ISSUE THREAD

**Issue by DabiaoMa** [CSTR-Edinburgh/merlin#261]
Hi, 

I am using World vocoder to reroduce wavs but it seems like World maybe not a good choice to produce high quality voices. I extracted acoustic features with World from original wavs then directly synthesized wavs with them. For most of the time the generated wavs are not good. 

Maybe I need to modify some parameters of World vocoder like frame shift or frame length, but with more synthesis time cost?

Can we use some other vocal models other than World or Straight? 

Deep mind declared that they created a new version of WaveNet that is 1000 times faster than the 
previous one, maybe the accelerated WaveNet is a good choice?

Tacotron uses a Griffin-Lim algorithm as vocoder, but I do not know whether Griffin-Lim performs better or not.
 
Best,

**Comment by ljuvela** [comment]
I recommend trying https://github.com/gillesdegottex/pulsemodel
It should be relatively straightforward to integrate into Merlin.

As for WaveNet, the latest DeepMind announcement contained virtually no information on what they have done. Let's wait for a paper. Anyway, most recent papers with WaveNet waveform generator (e.g. Baidu's stuff) use some acoustic features for local conditioning, so let's not give up on the old vocoders yet.  

Griffin-Lim is not really a vocoder, but rather a method to create consistent phase information for a magnitude spectrogram. So the quality there depends entirely on how well you can predict magnitude spectra (which is not too easy).

**Comment by DabiaoMa** [comment]
Thanks, I checked the paper 'Pulse Model in Log-domain for a Uniform Synthesizer', the author concludes that the Comparative mean opinion scores is a little worse than Straight.

Hope Deep mind would publish details soon...

**Comment by gillesdegottex** [comment]
For PML, using RNN and proper layer output, the results are eventually better, as shown in the journal article:
http://gillesdegottex.eu/wp-content/papercite-data/pdf/DegottexG2017pmlj_acceptedversion.pdf
(out since a week only).
Do not hesitate to ask me some new features for the code (feature extraction and synthesis options), I'll be surely happy to implement them.

Waveform synth is definitely a great solution for quality. The only problem is the technical "details" necessary to run this fast and the current feedback I got in conference about this is: "We can't speak about this". So you might have to wait quite a bit before getting details :(

Happy to read any other solution you find @DabiaoMa 

(Thanks @ljuvela !)

**Comment by fosimoes** [comment]
I was considering using MagPhase, which was recently presented at Interspeech.
https://github.com/CSTR-Edinburgh/magphase
MagPhase documentation has some guidelines on how to use it with Merlin. 
It suggests that running some scripts and changing Merlin's config file should be enough. I believe, however, that some modification in source code is necessary, since references to WORLD features (mgc, bap and lf0) are hard-coded into Merlin.
Has anyone tried to do it?

**Comment by dreamk73** [comment]
Interesting suggestions to check out. @fosimoes, you only need to add some code to merlin/src/configuration/configuration.py, where you will see settings for STRAIGHT and WORLD. You can define a different vocoder there in the same manner. You can define there what kind of parameter directories / files are used by the particular vocoder. I have tried it with GlottHMM and AHOcoder in the past.

**Comment by DabiaoMa** [comment]
@gillesdegottex Thanks and I will wait for the details

**Comment by felipeespic** [comment]
@fosimoes Yes, I have tried and works! You just need to add the MagPhase parameters (mag, real, imag and their deltas) in the configuration.py file with the dimensions: mag: 60, dmag: 180, real: 45, dreal: 135, imag: 45, dimag: 135.

I am currently working on the MagPhase-Merlin integration, but for now you can run the scripts manually as you mentioned. That should work.

**Comment by m-toman** [comment]
@felipeespic Do you need help with the integration?
I also planned to try it out.

Do you think MagPhase can be ported to C++ easily? And does it require access to the whole feature vector or can you run it streaming i.e. on chunks/windows?

Great to see so many vocoders coming out now, for years we've been mostly stuck with hts_engine and STRAIGHT ;)

**Comment by RasmusD** [comment]
MagPhase can be ported to C++ - whether it's easy to do is up to you ;-)

It can be run in individual frame chunks as well - so you can use it in a
streaming fashion - if you're doing a C++ implementation simply think that
in from the beginning :-)

2017-11-09 12:27 GMT+01:00 Markus Toman <notifications@github.com>:

**Comment by felipeespic** [comment]
Hi @m-toman , yes, I think I will need help for testing it. Could you help me with that?

Also, as @RasmusD  mentioned, you can implement MagPhase in C++ for streaming.
I think that it should be quite simple if you are proficient in C++.

**Comment by m-toman** [comment]
@RasmusD @felipeespic  
Well :)... let's see. I've briefly checked the source and the paper and guess it should be possible for me. I'm not very proficient with signal processing, but guess my C++ is OK (at least I ported the synthesis part of Merlin to C++).

@felipeespic Sure, would be glad to. I'm currently looking at the code and stepping through the merlin-preprocessing steps. Also started adapting the configuration.py.
I should be able to test it with a couple of voices with very different levels of quality.

**Comment by felipeespic** [comment]
Hi @m-toman , I just pushed the slt_arctic demo using MagPhase to the branch in my fork: https://github.com/felipeespic/merlin/tree/magphase_integration
It should work out of the box.

Could you test that everything works OK? Also, just if you have time, could you implement the slt_arctic full voice with MagPhase, please?

**Comment by m-toman** [comment]
@felipeespic OK thanks, should be able to check it out later today and guess should have the time to adapt the "full" version.

**Comment by dreamk73** [comment]
@felipeespic when running the script to extract magphase acoustic features with my 48000 Hz audio data, I get an error. But it confuses me because the value of fs is 48000 and yet it returns the ValueError at that point, when comparing fs != 48000 or fs != 16000?

python extract_features_for_merlin.py ~/merlin_magphase /data/esther/rs_merlin_data/sophie/wav48 /data/esther/rs_merlin_data/sophie/feat48_magphase 48000
Analysing file: sn001_sent001.wav................................
Extracting epochs with REAPER...
Residual symmetry: P:1713.454346  N:2288.913330  MEAN:0.044171
Traceback (most recent call last):
  File "extract_features_for_merlin.py", line 121, in <module>
    feat_extraction(wavfile, out_dir)
  File "extract_features_for_merlin.py", line 77, in feat_extraction
    m_mag_mel_log, m_real_mel, m_imag_mel, v_shift, v_lf0, fs = mp.analysis_with_del_comp__ph_enc__f0_norm__from_files2(wav_file, est_file, fft_len, mvf, f0_type='lf0', mag_mel_nbins=nbins_mel, cmplx_ph_mel_nbins=nbins_phase)
  File "/home/esther/merlin_magphase/tools/magphase/src/magphase.py", line 413, in analysis_with_del_comp__ph_enc__f0_norm__from_files2
    m_mag, m_real, m_imag, v_shift, v_voi, m_frms, fs  = analysis_with_del_comp__ph_enc__f0_norm__from_files_raw(wav_file, est_file, nFFT=nFFT, win_func=win_func)
  File "/home/esther/merlin_magphase/tools/magphase/src/magphase.py", line 393, in analysis_with_del_comp__ph_enc__f0_norm__from_files_raw
    raise ValueError('MagPhase works only at 16kHz and 48kHz sample rates, for now. The wavefile\'s sample rate is %d (Hz).\nConsider resampling the data beforehand if wanted.' % (fs))
ValueError: MagPhase works only at 16kHz and 48kHz sample rates, for now. The wavefile's sample rate is 48000 (Hz).

**Comment by dreamk73** [comment]
tools/magphase/src/magphase.py line 155

m_sp, m_ph, v_shift, m_frms, m_fft = analysis_with_del_comp_from_pm(v_in_sig, v_pm_smpls, nFFT, win_func=win_func, nwin_per_pitch_period=nwin_per_pitch_period)

should be

m_sp, m_ph, v_shift, m_frms, m_fft = analysis_with_del_comp_from_pm(v_in_sig, fs, v_pm_smpls, nFFT, win_func=win_func, nwin_per_pitch_period=nwin_per_pitch_period)

Also, that function only returns two variables and this line has five?

**Comment by dreamk73** [comment]
Change the return statement of analysis_with_del_comp_from_pm to have those five variables. Next issue is that the function get_fft_params_from_complex_data is not defined in magphase.py. I did have it in the previous version that you made but c&p it and running analysis gave lots of the same errors:

fft : m must be a integer of power of 2!

**Comment by felipeespic** [comment]
Hi @dreamk73 , Thank you for pointing out. Those functions do not work, because they are deprecated. 

I am moving this to the "Issues" section in my fork, since that code is not part of the Merlin repo yet. I will explain what's the problem and how to solve it in there. Thanks!

**Comment by ljuvela** [comment]
Details out on the Google's new production WaveNet:
https://deepmind.com/blog/high-fidelity-speech-synthesis-wavenet/

**Comment by felipeespic** [comment]
MagPhase vocoder integration with Merlin done in PR #281
