### ISSUE TITLE
No such file or directory error when running demo

### ISSUE THREAD

**Issue by leventunver** [CSTR-Edinburgh/merlin#269]
I just simply run the "run_demo.sh" in slt_arctic but below is the error that I get:

2017-11-01 14:04:07,646 INFO      acoustic_norm: Loaded min max values from the trained data for feature dimension of 416
2017-11-01 14:04:07,669 INFO           main    : label dimension is 416
2017-11-01 14:04:07,669 INFO           main    : generating from DNN
Traceback (most recent call last):
  File "/home/ubuntu/merlin-master/src/run_merlin.py", line 1224, in <module>
    main_function(cfg)
  File "/home/ubuntu/merlin-master/src/run_merlin.py", line 895, in main_function
    dnn_generation(test_x_file_list, nnets_file_name, lab_dim, cfg.cmp_dim, gen_file_list, reshape_io)
  File "/home/ubuntu/merlin-master/src/run_merlin.py", line 418, in dnn_generation
    dnn_model = pickle.load(open(nnets_file_name, 'rb'))
IOError: [Errno 2] No such file or directory: '/home/ubuntu/merlin-master/egs/slt_arctic/s1/experiments/slt_arctic_demo/duration_model/nnets_model/feed_forward_4_tanh.model'

Any ideas? Thanks...

**Comment by seblemaguer** [comment]
Hello, did you check if anything before crashed? It seems the duration model is not saved

**Comment by leventunver** [comment]
I resigned from the company that I work for before I look deep into this problem. But as far as I've heard it's been solved, I just don't know how. Sorry for the inconvenience.

**Comment by adilkhanovkz** [comment]
Thank you for response. I looked at the code and found that in train script the model will be saved if it will reach minimum validation loss AFTER 5 epochs. Otherwise the model will not be saved.
