### ISSUE TITLE
[build_your_own_voice] AssertionError: check train, valid, test file number

### ISSUE THREAD

**Issue by khacpv** [CSTR-Edinburgh/merlin#271]
I'm trying to build and run **build_your_own_voice** egs
It's failed on step 5:
`./05_train_duration_model.sh conf/duration_slt_arctic.conf`

error output:
```
Traceback (most recent call last):
  File "/media/psf/Home/Workspaces/python_workspace/merlin/src/run_merlin.py", line 1229, in <module>
    main_function(cfg)
  File "/media/psf/Home/Workspaces/python_workspace/merlin/src/run_merlin.py", line 516, in main_function
    assert cfg.train_file_number+cfg.valid_file_number+cfg.test_file_number == total_file_number, 'check train, valid, test file number'
AssertionError: check train, valid, test file number
```
Then I tried to print out values: `run_merlin.py#516`
```
cfg.train_file_number: 50
cfg.valid_file_number: 5
cfg.test_file_number: 5
total_file_number: 53
```
I think cause is from: `file_id_list.scp`
`$cat experiments/slt_arctic/duration_model/data/file_id_list.scp`
```
arctic_a0003
arctic_a0004
arctic_a0005
arctic_a0006
arctic_a0007
arctic_a0008
arctic_a0009
arctic_a0010
arctic_a0011
arctic_a0012
arctic_a0013
arctic_a0014
arctic_a0015
arctic_a0019
arctic_a0020
arctic_a0021
arctic_a0022
arctic_a0024
arctic_a0026
arctic_a0027
arctic_a0028
arctic_a0029
arctic_a0030
arctic_a0031
arctic_a0032
arctic_a0033
arctic_a0034
arctic_a0035
arctic_a0036
arctic_a0037
arctic_a0038
arctic_a0039
arctic_a0040
arctic_a0041
arctic_a0042
arctic_a0043
arctic_a0044
arctic_a0045
arctic_a0046
arctic_a0047
arctic_a0048
arctic_a0049
arctic_a0050
arctic_a0051
arctic_a0052
arctic_a0053
arctic_a0054
arctic_a0055
arctic_a0056
arctic_a0057
arctic_a0058
arctic_a0059
arctic_a0060
```
there are only 53 files, I don't know why but it makes assertion failed.
Anyone could help me where's my wrong? or same problem with me?

**Comment by chazo1994** [comment]
You should check your config file. As I see, you have wrong configuration, you have 53 files but you config 50 file to train, 5 file to test and 5 file to valid ==> 50 + 5 + 5 > 53, it make this error. So change your config same like below:
cfg.train_file_number: 47
cfg.valid_file_number: 3
cfg.test_file_number: 3

**Comment by khacpv** [comment]
Thanks @chazo1994 , It worked!
