### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'database/feats/f0/wan_a.f0_world'

### ISSUE THREAD

**Issue by syazw** [CSTR-Edinburgh/merlin#274]
wan_a
This function cannot support stereo file
error: The file is not .wav format.
Running REAPER f0 extraction...
sh: 1: /home/zainursyazwana/audio_wan/merlin/tools/bin/REAPER/reaper: not found
Traceback (most recent call last):
  File "/home/zainursyazwana/audio_wan/merlin/misc/scripts/vocoder/world/extract_features_for_merlin.py", line 216, in <module>
    pool.map(process, wav_files)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
IOError: [Errno 2] No such file or directory: 'database/feats/f0/wan_a.f0_world'
Copying features to acoustic data directory...
done...!
##################################################################

Hi @ronanki , I got this error, when i tried to run ./03_prepare_acoustic_features.sh database/wav database/feats . So, how to fix this error? Thanks for your help.

**Comment by felipeespic** [comment]
Hi @syazw , Did you installed REAPER?
Also, if your files are stereo, convert them to mono before extracting features.

**Comment by HandsomeDevilv112** [comment]
where was the installation file/instructions for REAPER?

**Comment by Jackiexiao** [comment]
if you install REAPER successfully, you could find REAPER in `merlin/tools/REAPER`, otherwise, see `merlin/tools/compile_tools.sh` which install REAPER as well as other essential tools like htk world sptk

**Comment by HandsomeDevilv112** [comment]
it's been a number of months, but I just know I did compile_tools/compile_other_tools/compile_htk/compile_compile_compile. 
Apologies, friend. I have periodic fits of illiteracy.

**Comment by Maxxiey** [comment]
Hi, @HandsomeDevilv112 @Jackiexiao , I got the same error here, I checked the REAPER directory and all seemed to be normal. I successfully trained merlin on a little dataset, but when I tried to use a bigger one(more than 10000), the error was raised.

How did you guys solve that problem?
thanks in advance.

**Comment by RasmusD** [comment]
@Maxxiey 
If youre error is the exact same as the initially reported error.
Then at least 1 of your wav files is a stereo file. Probably one in the larger dataset. Convert it to mono.

**Comment by Maxxiey** [comment]
@RasmusD 
Thanks and sorry for the late reply, I checked out the log and find that there were error messages like '**.wav is not wav format'. I searched the issue list and pinpointed that the error was raised because some of the wav files contained metadata, and the script can not recognise those wav files. I used ffmpeg to remove the metadata part and everything went right.

And yes, if the wav files are stereo, there will be problems, need to convert them first~
