### ISSUE TITLE
ImportError: No module named bandmat

### ISSUE THREAD

**Issue by saurabhvyas** [CSTR-Edinburgh/merlin#299]
I was following along this tutorial , http://jrmeyer.github.io/tts/2017/02/14/Installing-Merlin.html

saurabh@saurabh-Inspiron-5559:~/merlin/egs/slt_arctic/s1$ sudo ./03_train_duration_model.sh conf/duration_slt_arctic_demo.conf
Step 3:
training duration model...
Architecture: x86_64
Distribution: Ubuntu 16.04.3 LTS
HOSTNAME=saurabh-Inspiron-5559
USER=root
 
PATH:
    /usr/local/sbin
    /usr/local/bin
    /usr/sbin
    /usr/bin
    /sbin
    /bin
    /snap/bin
LD_LIBRARY_PATH:
PYTHONPATH:
PYTHONBIN: python
MERLIN_THEANO_FLAGS:
    cuda.root=/usr/local/8.0
    floatX=float32
    on_unused_input=ignore
 
No GPU is available! Running on CPU...
Traceback (most recent call last):
  File "/home/saurabh/merlin/src/run_merlin.py", line 64, in <module>
    from frontend.parameter_generation import ParameterGeneration
  File "/home/saurabh/merlin/src/frontend/parameter_generation.py", line 50, in <module>
    from .mlpg_fast import MLParameterGenerationFast as MLParameterGeneration
  File "/home/saurabh/merlin/src/frontend/mlpg_fast.py", line 53, in <module>
    import bandmat as bm
ImportError: No module named bandmat

**Comment by ljuvela** [comment]
It seems you are missing the bandmat python module. Make sure to install all the dependencies listed in https://github.com/CSTR-Edinburgh/merlin/blob/master/requirements.txt.

For more info on this specific module, see https://pypi.python.org/pypi/bandmat

**Comment by saurabhvyas** [comment]
Okay, so I checked I have bandmat installed, here is the problem , when I run ./run_demo.sh , it uses my default python (3.6.1) and says permission denied, when I run sudo ./run_demo.sh , it uses python 2.7 and says bandmat not found, is there a way to use python 3.6 and still run the script ?

Here are the logs , when I run without sudo 

``` t value .imag
2018-01-18 14:03:40,373     INFO  configuration:   Extensions:dur_ext has default value .dur
Traceback (most recent call last):
  File "/home/saurabh/merlin/src/run_merlin.py", line 1194, in <module>
    cfg.configure(config_file)
  File "/home/saurabh/merlin/src/configuration/configuration.py", line 91, in configure
    self.logging_configuration()
  File "/home/saurabh/merlin/src/configuration/configuration.py", line 1092, in logging_configuration
    os.makedirs(self.log_path, 0o755)
  File "/home/saurabh/anaconda3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/home/saurabh/merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/duration_model/log'

```

**Comment by saurabhvyas** [comment]
Update :  Installing merlin on virtualenv fixed the problem
