### ISSUE TITLE
Phone_alignment CRITICAL computer_distortion frame number are not same 

### ISSUE THREAD

**Issue by ajinkyakulkarni14** [CSTR-Edinburgh/merlin#306]
I was trying to run slt_arctic demo for phone_align_labels. I made changes in duration and acoustic conf files, state_label to phone_label. 
[conf_files.zip](https://github.com/CSTR-Edinburgh/merlin/files/1723766/conf_files.zip)

I am getting following error message 

2018-02-14 12:29:23,256 CRITICALcomputer_distortion: The number of frames is not the same: 763 vs 45 (arctic_a0051). Error in compute_distortion.py
.
Traceback (most recent call last):
  File "/home/ajinkyak/speech_synthesis/merlin/merlin/src/run_merlin.py", line 1270, in <module>
    main_function(cfg)
  File "/home/ajinkyak/speech_synthesis/merlin/merlin/src/run_merlin.py", line 1033, in main_function
    valid_spectral_distortion = calculator.compute_distortion(valid_file_id_list, ref_data_dir, gen_dir, cfg.mgc_ext, cfg.mgc_dim)
  File "/home/ajinkyak/speech_synthesis/merlin/merlin/src/utils/compute_distortion.py", line 181, in compute_distortion
    raise
RuntimeError: No active exception to reraise

PS: System is getting trained well with state_align labels but not with phone_label. I am sharing my configuration files.

Any recommendation regards to changes in config file will appreciated.

**Comment by 1271086950** [comment]
hello,Have you solved this problem?

**Comment by antontc** [comment]
hi. I have the same problem
