### ISSUE TITLE
Speechtools - error importing python wrapper for hybrid synthesis

### ISSUE THREAD

**Issue by fosimoes** [CSTR-Edinburgh/merlin#312]
This problem has been reported in past issues, but no solution has been presented.
Hope somebody can help me with that.

I get the following errors when importing some of the speechtools python wrappers:

ImportError: ./_EST_Wave.so: undefined symbol: _ZN8EST_Wave19default_sample_rateE
ImportError: ./_EST_Utterance.so: undefined symbol: est_errjmp

Any clues?

**Comment by m-toman** [comment]
Unfortunately I can't help - I'm currently also dealing with that issue and it seems there are a potential dozen reasons for it to happen.

Currently I assume you need the correct constellation of python, gcc, swig etc. for it to work out - I tried it with a few different settings now (Ubuntu, Mint, Mac OS X, Python 2 and 3, running swig during the makefile, getting the latest gcc etc.) but no luck yet.

**Comment by licktion** [comment]
I got the error like this. Need help also. Thanks in advance!

Traceback (most recent call last):
  File "/home/ubuntu/speech-synthesis/tools/multisyn_build/bin/add_noise", line 43, in <module>
    import EST_Wave
  File "/home/ubuntu/speech-synthesis/tools/speech_tools/wrappers/python/EST_Wave.py", line 25, in <module>
    _EST_Wave = swig_import_helper()
  File "/home/ubuntu/speech-synthesis/tools/speech_tools/wrappers/python/EST_Wave.py", line 17, in swig_import_helper
    import _EST_Wave
ImportError: No module named _EST_Wave

**Comment by fosimoes** [comment]
What I have found out so far:

apparently, the python wrappers are not linking with speechtools/lib/libestbase, which is the library where the unrecognized symbols are defined. I don't understand why this happens, though, since I have no compiler/linker warnings.

I don't know if libestbase should be linked statically or dinamically to the wrappers, neither how to force the appropriate linking. 

Any kind of help will be aprreciated!

**Comment by licktion** [comment]
Same error here. I'm not sure if it's system-related, but I do see some cases like failed in Ubuntu 17 but successful in Centos 7. If anyone succeeds in Ubuntu 16, please let me know. Thanks in advance!

**Comment by lehaison** [comment]
It happens to me too with http://www.cstr.ed.ac.uk/downloads/festival/2.4/speech_tools-2.4-with-wrappers.tar.gz, Ubuntu 16
My solution is to modify this file: speech_tools-2.4-with-wrappers/wrappers/python/Makefile:
At line 87, change from: $(subst XXX,$@,$(MAKE_SHARED_LIB)) $(LIBS) $< 
to: $(subst XXX,$@,$(MAKE_SHARED_LIB)) $< $(LIBS)
because with gcc in Ubuntu, the dependency order is important.
The gcc command will be changed from:
gcc -shared -o _EST_Wave.so -L../../lib -lestools -L../../lib -lestbase -L../../lib -leststring   -lncurses   -ldl -lncurses -lm  -lstdc++ EST_Wave_wrap.o
to:
gcc -shared -o _EST_Wave.so EST_Wave_wrap.o   -L../../lib -lestools -L../../lib -lestbase -L../../lib -leststring   -lncurses   -ldl -lncurses -lm  -lstdc++
Then before importing this library, don't forget to add the directory containing libest*.so to LD_LIBRARY_PATH (speech_tools-2.4-with-wrappers/lib/)
