### ISSUE TITLE
Force-alignment unsucessful!!

### ISSUE THREAD

**Issue by martedva** [CSTR-Edinburgh/merlin#313]
Hello,

I am trying to create my own voice with 'build_your_own_voice'.

I have made it through the first script, '01_setup.sh', but I am stuck at the second one, '02_prepare_labels.sh'. You can see the error in the attached picture. 

![screenshot from 2018-03-15 22-04-05](https://user-images.githubusercontent.com/6831315/37491219-6396329c-289d-11e8-80b0-259c91f5124e.png)

I have configured my 'global_settings.cfg'-file to match my data, with the correct paths, as shown below.

![screenshot from 2018-03-15 22-09-12](https://user-images.githubusercontent.com/6831315/37491259-8336a71c-289d-11e8-8204-f5be1be4eea7.png)

Any ideas for a solution for this problem?

Thanks in advance,
Martin

**Comment by wooters** [comment]
Does it work if you use full path names when you call `02_prepare_labels.sh`? Something like:
```
./02_prepare_labels.sh /home/tts/merlin/egs/build_your_own_voice/s1/database/wav \
   /home/tts/merlin/egs/build_your_own_voice/s1/database/txt \
   /home/tts/merlin/egs/build_your_own_voice/s1/database/labels
```

**Comment by m-toman** [comment]
And was building HTK successful? (i.e. is the HCopy binary available?)

**Comment by martedva** [comment]
@wooters This did not work either, no - I tried that too.

@m-toman HTK should be successfully built. I have an HCopy in the HTKTools folder?

**Comment by seblemaguer** [comment]
you should have HCopy there: <merlin_root_dir>/tools/bin/htk/HCopy

**Comment by martedva** [comment]
Sorry for late response, @seblemaguer. Your suggested HCopy location does not change the error message.

**Comment by seblemaguer** [comment]
on my side, I used the default configuration. This leads to this configuration (with the merlin directory being `/merlin`):

```ini
######################################
############# TOOLS ##################
######################################

ESTDIR=/merlin/tools/speech_tools
FESTDIR=/merlin/tools/festival
FESTVOXDIR=/merlin/tools/festvox

HTKDIR=/merlin/tools/bin/htk
```

At the end of `compile_htk.sh`, I have that (once again I didn't touch anything, that is the file from the repo):

```sh
HTK_BIN_DIR=$tools_dir/bin/htk

mkdir -p $tools_dir/bin
mkdir -p $HTK_BIN_DIR

cp $tools_dir/htk/build/bin/* $HTK_BIN_DIR/

if [[ ! -f ${HTK_BIN_DIR}/HVite ]]; then
    echo "Error installing HTK tools"
    exit 1
else
    echo "HTK successfully installed...!"
fi
```

That is why I indicated to check if `<merlin_root_dir>/tools/bin/htk/HCopy` exists.

As you pointed out, you are using a different location which is `<merlin_root_dir>/tools/htk/HCopy`. I didn't pay attention to that so I missed this point (sorry for that). So based on this info you have to check that this file exists and is executable.

In any case, I would suggest to try to keep as much as possible close to the repository configuration.

**Comment by martedva** [comment]
Hi, @seblemaguer!

It seems to be working now, however, i now get the following segmentation fault, when i try to run the WORLD-script, './extract_features_for_merlin.sh':

![image](https://user-images.githubusercontent.com/6831315/37598786-7248140c-2b83-11e8-842a-69912b83df83.png)

This happens for the same files every time I run them - 100, 118, 235, 341:
 - .wav and .txt works and are correct.
 - all labels exist for everyone of them.
 - it exists in the file_id_list.scp

Any thoughts?

Thanks again in advance!

**Comment by martedva** [comment]
Quick update @seblemaguer!

I now simply removed these files and was able to continue, but now i get the following problem.

```
Problem occurred during compilation with the command line below:
/usr/bin/g++ -shared -g -O3 -fno-math-errno -Wno-unused-label -Wno-unused-variable -Wno-write-strings -Wl,-rpath,/home/tts/anaconda2/lib -march=haswell -mmmx -mno-3dnow -msse -msse2 -msse3 -mssse3 -mno-sse4a -mcx16 -msahf -mmovbe -maes -mno-sha -mpclmul -mpopcnt -mabm -mno-lwp -mfma -mno-fma4 -mno-xop -mbmi -mbmi2 -mno-tbm -mavx -mavx2 -msse4.2 -msse4.1 -mlzcnt -mrtm -mhle -mrdrnd -mf16c -mfsgsbase -mno-rdseed -mno-prfchw -mno-adx -mfxsr -mxsave -mxsaveopt -mno-avx512f -mno-avx512er -mno-avx512cd -mno-avx512pf -mno-prefetchwt1 -mno-clflushopt -mno-xsavec -mno-xsaves -mno-avx512dq -mno-avx512bw -mno-avx512vl -mno-avx512ifma -mno-avx512vbmi -mno-clwb -mno-pcommit -mno-mwaitx --param l1-cache-size=32 --param l1-cache-line-size=64 --param l2-cache-size=6144 -mtune=haswell -DNPY_NO_DEPRECATED_API=NPY_1_7_API_VERSION -m64 -fPIC -I/home/tts/anaconda2/lib/python2.7/site-packages/numpy/core/include -I/home/tts/anaconda2/include/python2.7 -I/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/c_code -L/home/tts/anaconda2/lib -L/home/tts/anaconda2/lib -fvisibility=hidden -o /home/tts/.theano/compiledir_Linux-4.13--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.14-64/tmp8jF3wP/b8e34ea4363b3812bd111a731cb835f81ccc84235ec10367467e6198f7abc278.so /home/tts/.theano/compiledir_Linux-4.13--generic-x86_64-with-debian-stretch-sid-x86_64-2.7.14-64/tmp8jF3wP/mod.cpp -lmkl_core -lmkl_gnu_thread -lmkl_rt -lpython2.7
2018-03-19 18:07:11,609 CRITICAL       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/home/tts/merlin/src/run_merlin.py", line 1308, in <module>
    main_function(cfg)
  File "/home/tts/merlin/src/run_merlin.py", line 858, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector,init_dnn_model_file=cfg.start_from_trained_model)
  File "/home/tts/merlin/src/run_merlin.py", line 285, in train_DNN
    (train_set_x, train_set_y), (valid_set_x, valid_set_y), use_lhuc, layer_index=cfg.freeze_layers)  #, batch_size=batch_size
  File "/home/tts/merlin/src/models/deep_rnn.py", line 253, in build_finetune_functions
    self.is_train: np.cast['int32'](1)}, on_unused_input='ignore')
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/compile/function.py", line 317, in function
    output_keys=output_keys)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/compile/pfunc.py", line 486, in pfunc
    output_keys=output_keys)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1841, in orig_function
    fn = m.create(defaults)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/compile/function_module.py", line 1715, in create
    input_storage=input_storage_lists, storage_map=storage_map)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/link.py", line 699, in make_thunk
    storage_map=storage_map)[:3]
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/vm.py", line 1084, in make_all
    impl=impl))
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 955, in make_thunk
    no_recycling)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/op.py", line 858, in make_c_thunk
    output_storage=node_output_storage)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1217, in make_thunk
    keep_lock=keep_lock)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1157, in __compile__
    keep_lock=keep_lock)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1620, in cthunk_factory
    key=key, lnk=self, keep_lock=keep_lock)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 1174, in module_from_key
    module = lnk.compile_cmodule(location)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/cc.py", line 1523, in compile_cmodule
    preargs=preargs)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/gof/cmodule.py", line 2314, in compile_str
    p_out = output_subprocess_Popen(cmd)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/misc/windows.py", line 77, in output_subprocess_Popen
    p = subprocess_Popen(command, **params)
  File "/home/tts/anaconda2/lib/python2.7/site-packages/theano/misc/windows.py", line 43, in subprocess_Popen
    proc = subprocess.Popen(command, startupinfo=startupinfo, **params)
  File "/home/tts/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/home/tts/anaconda2/lib/python2.7/subprocess.py", line 917, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Lock freed
tts@tts:~/merlin/egs/build_your_own_voice/s1$
```

Thanks in advance,
