### ISSUE TITLE
AHOCODER implementation

### ISSUE THREAD

**Issue by akfalc** [CSTR-Edinburgh/merlin#326]
Hi There!

I am trying merlin with ahocoder and as I got outputs with extensions '.cc' '.fv' and '.fo'  I tried to change configure.py based on given parameters but I always got the below error
merlin/src/run_merlin.py", line 645
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, cfg.in_dimension_dict, cfg.out_dimension_dict)
                                                                                                                      ^
IndentationError: unindent does not match any outer indentation level
I tried to solve it but It seems like I do not see something so any help would be great.

Thanks in advance.

**Comment by ljuvela** [comment]
Python syntax is sensitive to indentation levels and your IndentationError is likely related to that. 

I don’t know which code editor you use, but Ubuntu’s default text editors are pretty tedious for Python. Maybe give vscode or emacs a try?

**Comment by akfalc** [comment]
Thank you for the help now the syntax problem seems to be solved. However I have another issue.
Traceback (most recent call last):
  File "/home/akfalc/merlin/src/run_merlin.py", line 1336, in <module>
    main_function(cfg)
  File "/home/akfalc/merlin/src/run_merlin.py", line 680, in main_function
    global_mean_vector = normaliser.compute_mean(nn_cmp_file_list[0:cfg.train_file_number], 0, cfg.cmp_dim)
  File "/home/akfalc/merlin/src/frontend/mean_variance_norm.py", line 137, in compute_mean
    features, current_frame_number = io_funcs.load_binary_file_frame(file_name, self.feature_dimension)
  File "/home/akfalc/merlin/src/io_funcs/binary_io.py", line 64, in load_binary_file_frame
    fid_lab = open(file_name, 'rb')
IOError: [Errno 2] No such file or directory: '/home/akfalc/merlin/egs/voice_conversion/s1/experiments/jmk/acoustic_model/inter_module/nn_cc_fo_vuv_fv_254/arctic_a0001.cmp'
well as I know ahocoder's outputs have different dimension than world vocoder that's why I have changed something on confıguration.py  but above error appears and I couldn't solve it yet.

Any help will be appriciated.
