### ISSUE TITLE
AHOCODER implementation Problem

### ISSUE THREAD

**Issue by akfalc** [CSTR-Edinburgh/merlin#335]
When I try to run network with AHOCODER feature vectors .cc .fv .f0 I got following error.

018-04-10 11:46:52,136 CRITICAL  configuration: please provide the path for vuv feature
Traceback (most recent call last):
  File "/home/akfalc/merlin/src/run_merlin.py", line 1260, in <module>
    cfg.configure(config_file)
  File "/home/akfalc/merlin/src/configuration/configuration.py", line 95, in configure
    self.complete_configuration()
  File "/home/akfalc/merlin/src/configuration/configuration.py", line 912, in complete_configuration
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
Lock freed

What can be the solution for this issue ?

Thanks in advance.

**Comment by ljuvela** [comment]
Merlin doesn't seem to write anything to the `in_directory` variable in the `'vuv'` branch. This is a likely cause for your error.

Don't know why `'vuv'` is treated like this, is it a bug or some special treatment? @ronanki @bajibabu 

https://github.com/CSTR-Edinburgh/merlin/blob/0897e6d8b31e9e3a5bef45ce1b5cf0821bfd09c3/src/configuration/configuration.py#L733-L746
