### ISSUE TITLE
Problem With LSTM LHUC Speaker Adaptation

### ISSUE THREAD

**Issue by martedva** [CSTR-Edinburgh/merlin#340]
Hi
I have a problem when trying to perform speaker adaptation using LHUC.
When building the model in step 12 I get the following error message:
 ```
2018-04-12 15:08:25,883 CRITICAL       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/home/tts/merlin/src/run_merlin.py", line 1313, in <module>
    main_function(cfg)
  File "/home/tts/merlin/src/run_merlin.py", line 863, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector,init_dnn_model_file=cfg.start_from_trained_model)
  File "/home/tts/merlin/src/run_merlin.py", line 246, in train_DNN
    dropout_rate = dropout_rate, optimizer = cfg.optimizer, rnn_batch_training = cfg.rnn_batch_training)
  File "/home/tts/merlin/src/models/deep_rnn.py", line 119, in __init__
    hidden_layer = VanillaLstm_LHUC(rng, layer_input, input_size, hidden_layer_size[i], p=self.dropout_rate, training=self.is_train, rnn_batch_training=self.rnn_batch_training)
TypeError: __init__() got an unexpected keyword argument 'rnn_batch_training'
```

How would one go about fixing this?

**Comment by bajibabu** [comment]
The 'rnn_batch_training' keyword is not present in lhuc layer. Can you remove that option and run the model again. Someone accidentally added that keyword without testing.

**Comment by bajibabu** [comment]
hi, I didn't encounter this kind of error before. I don't know whether you got the error due to latest version of theano or other. Could you double check the dimensions of your parameters

**Comment by martedva** [comment]
@bajibabu 
I have Theano version 1.0.1 installed, and it have worked just fine until now. I used LHUC successfully with a feed forward AVM last week. The problem seems to be specifically with the LSTM_LHUC layer.
I don't know if you by parameters mean the dimensionality of the input given to the duration model or the parameters for the _init_ function in the LSTM_LHUC layer?

Nonetheless, the input label dimensions is 416 for the duration model - I haven't touched the dimensionality of that, so that should just be the default dimensionality.
And as for the _init_ function these are the values given to it during the building of the network:
x: Shape.0
n_in: 1024
n_h: 768
p: 0.0
training: is_train

I have been comparing the normal LstmBase implementation with the corresponding LHUC implementation, and can't see any differences beside the scaling factor. The scan function, which is where it fails, is exactly the same in both files.

**Comment by martedva** [comment]
I think I fixed the problem by overwriting everything in LstmBase_LHUC with the implementation from LstmBase except the scaling factor and how it affects the output. The theano.scan call no longer makes the implementation crash.
However, now I get an error after the first epoch has been successfully completed.
It seems like Merlin is stuck in a recursive loop while saving the model, which makes it crash due to a stackoverflow.
Have you seen this before?
Thanks in advance!

```
File "/home/tts/merlin/src/run_merlin.py", line 1313, in <module>
    main_function(cfg)
  File "/home/tts/merlin/src/run_merlin.py", line 863, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector,init_dnn_model_file=cfg.start_from_trained_model)
  File "/home/tts/merlin/src/run_merlin.py", line 384, in train_DNN
    pickle.dump(best_dnn_model, open(nnets_file_name, 'wb'))
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 1376, in dump
    Pickler(file, protocol).dump(obj)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 669, in _batch_setitems
    save(v)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/home/tts/anaconda2/lib/python2.7/pickle.py", line 425, in save_reduce
    save(state)
...
RuntimeError: maximum recursion depth exceeded
```

**Comment by martedva** [comment]
It seems that adding the following line of code to line 384 in ``run_merlin.py`` solves the last problem.
Note that one should be careful adding this line, as it may crash merlin depending on ones CPU and available stack space.

Thank you @bajibabu ,for taking your time to answer me.

**Comment by bajibabu** [comment]
Hey, sorry that I could not able to help you much in this issue. Anyway, you found the solution, that's great (+1). Could you please tell us what line did you add in run_merlin.py.

**Comment by martedva** [comment]
@bajibabu, Oh my bad, I totally forgot to add the line. I updated the comment with the line.
