### ISSUE TITLE
Voice Conversion - Not converging after 50 epochs 

### ISSUE THREAD

**Issue by vivek-sethia** [CSTR-Edinburgh/merlin#344]
How many epochs are required to get a decent voice conversion? 
I am using the default dataset of CMU Arctic and folllowed all the steps but the converted voice are not all audible.

**Comment by felipeespic** [comment]
Hi, which recipe are you using (s1 or s2)?

**Comment by felipeespic** [comment]
Didn't you try with s2?

**Comment by vivek-sethia** [comment]
Is s2 recipe works with python 2? Since I am facing a lot of error beacuse of python 3

**Comment by felipeespic** [comment]
Yes, I think so, Python 2.7

**Comment by vivek-sethia** [comment]
After creating new environment with python 2.7 and running s2 script, I got stuck in the second step

Here is the log 

```
Prepare acoustic features using MAGPHASE vocoder...


Analysing file: arctic_a0020.wav................................
Analysing file: arctic_a0001.wav................................

Analysing file: arctic_a0039.wav................................

Analysing file: arctic_a0058.wav................................
Extracting epochs with REAPER...
Extracting epochs with REAPER...
Extracting epochs with REAPER...
Extracting epochs with REAPER...
Residual symmetry: P:1057.966064  N:2080.696289  MEAN:-1.834260
Residual symmetry: P:779.040894  N:1617.814087  MEAN:-0.248217
Residual symmetry: P:565.581360  N:1208.755005  MEAN:0.239541
Residual symmetry: P:593.399414  N:1381.622070  MEAN:0.091667
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
Traceback (most recent call last):
  File "/home/ubuntu/merlin/misc/scripts/vocoder/magphase/extract_features_for_merlin.py", line 82, in <module>
    lu.run_multithreaded(feat_extraction, l_wavfiles, out_dir)
  File "/home/ubuntu/merlin/tools/magphase/src/libutils.py", line 62, in run_multithreaded
    results = pool.map(func_wrapper, l_iterable_args)
  File "/home/ubuntu/anaconda2/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/ubuntu/anaconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
ValueError: operands could not be broadcast together with shapes (0,10) (396,1) 
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
/bin/sh: 1: /home/ubuntu/merlin/tools/magphase/tools/bin/mcep: not found
```

**Comment by vivek-sethia** [comment]
I checked my folder /merlin/tools/bin/SPTK-3.9, it is empty. Do you think I missed some step of installation?

**Comment by vivek-sethia** [comment]
Finally the scripts after installing csh which was the cause of my SPTK installation fail and hence other issues arose.

I was able to use s2 script for voice conversion. Thanks @felipeespic

**Comment by felipeespic** [comment]
You are welcome

**Comment by vivek-sethia** [comment]
The demo recipe did work but it doesn't not work with other data I am using. You can find the wav files [here](https://drive.google.com/open?id=1kKDrEw5rV_q0ha5CyGIqR4G1JceD8JaR)

**Comment by vivek-sethia** [comment]
@felipeespic  Also if I can find out some documentation or tutorials regarding this voice conversion method provided here, it would be nice to understand the overall process.

**Comment by felipeespic** [comment]
I realised that actually it was just a warning, so it shouldn't affect the performance. Anyway, I just got rid of that warning and [I pushed it to the master](https://github.com/CSTR-Edinburgh/magphase/commit/5b2096304938a707187e5211c6979659b657d5f1), so you can download the new version of _MagPhase_ if wanted.

For the documentation, unfortunately I don't have any by now, but if I find something I will post it.

Thanks

**Comment by vivek-sethia** [comment]
@felipeespic  Do you think I can use this as recipe for emotonal voice conversion, i.e neutral to emotional speech? 

If yes, can you give some hints. I am reading this paper about https://www.researchgate.net/publication/306928922_Emotional_voice_conversion_using_deep_neural_networks_with_MCC_and_F0_features and was thinking if could use a similar approach with this tool.

**Comment by vivek-sethia** [comment]
@felipeespic  Thank you for the recipe and supporting regularly with the issues.

Is it possible talk to you on Gitter for some time, so that I can clarify few of the things. It will be not long, I will just need to ask few things. 

Since that will help me a bit to get a clear picture of the recipe and also the possibilities.

**Comment by felipeespic** [comment]
Yes, I am connected now actually.
