### ISSUE TITLE
Issue after Feature Extraction using VCTK DATASET

### ISSUE THREAD

**Issue by vinaykumarbundla** [CSTR-Edinburgh/merlin#356]
echo 'All successfull!! Your demo voice is ready :)'
All successfull!! Your demo voice is ready :)
Feature extraction complete!

Traceback (most recent call last):
  File "extract_features.py", line 1406, in <module>
    save_numpy_features()
  File "extract_features.py", line 853, in save_numpy_features
    shutil.copy2(audio_norm_source, audio_norm_dest)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/mcis-lap-3/PycharmProjects/speakerrecoginition/latest_features/final_acoustic_data/norm_info_mgc_lf0_vuv_bap_63_MVN.dat'

**Comment by shuzeZHAO** [comment]
same issue here

**Comment by seblemaguer** [comment]
do you have any files in '/home/mcis-lap-3/PycharmProjects/speakerrecoginition/latest_features/final_acoustic_data/' ?
