### ISSUE TITLE
final stage of acoustic training fails for slt_srctic s2

### ISSUE THREAD

**Issue by saurabhvyas** [CSTR-Edinburgh/merlin#361]
```
2018-05-14 16:56:16,512 INFO      acoustic_norm: Loaded min max values from the trained data for feature dimension of 425
2018-05-14 16:56:16,569 INFO           main    : label dimension is 425
2018-05-14 16:56:16,569 INFO           main    : generating from DNN
2018-05-14 16:56:16,583 INFO     dnn_generation: generating    1 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0056.lab
2018-05-14 16:56:17,649 INFO     dnn_generation: generating    2 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0057.lab
2018-05-14 16:56:17,782 INFO     dnn_generation: generating    3 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0058.lab
2018-05-14 16:56:17,929 INFO     dnn_generation: generating    4 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0059.lab
2018-05-14 16:56:18,059 INFO     dnn_generation: generating    5 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0060.lab
2018-05-14 16:56:18,205 INFO    param_generation: processing    1 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0056.cmp
2018-05-14 16:56:18,241 INFO    param_generation: processing    2 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0057.cmp
2018-05-14 16:56:18,273 INFO    param_generation: processing    3 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0058.cmp
2018-05-14 16:56:18,323 INFO    param_generation: processing    4 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0059.cmp
2018-05-14 16:56:18,355 INFO    param_generation: processing    5 of    5: /mnt/orangedrive2/merlin/egs/slt_arctic/s2/experiments/slt_arctic_magphase_demo_mag_dim_100_phase_dim_10_const_rate_0/test_synthesis/gen_acous/arctic_a0060.cmp
2018-05-14 16:56:18,381 INFO           main    : reconstructing waveform(s)
Traceback (most recent call last):
  File "/mnt/orangedrive2/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/mnt/orangedrive2/merlin/src/run_merlin.py", line 989, in main_function
    generate_wav(gen_dir, gen_file_id_list, cfg)     # generated speech
  File "/mnt/orangedrive2/merlin/src/utils/generate.py", line 328, in generate_wav
    wavgen_magphase(gen_dir, file_id_list, cfg, logger)
  File "/mnt/orangedrive2/merlin/src/utils/generate.py", line 302, in wavgen_magphase
    import libaudio as la

File "/mnt/orangedrive2/merlin/tools/magphase/src/libaudio.py", line 887
    raise ValueError, "smooth only accepts 1 dimension arrays."

```

I have installed all dependencies, and tried using both python2 and python3

**Comment by saurabhvyas** [comment]
I tried again with s1 scripts work fine, and I am able to perform test inference

**Comment by saurabhvyas** [comment]
I am afraid I have moved on to some other project, so dont have time to test it, if you have tested it, it mist be correct.
