### ISSUE TITLE
Codec error when processing .lab files

### ISSUE THREAD

**Issue by marianatuma** [CSTR-Edinburgh/merlin#362]
Hi all. I'm working with the `speaker_adaptation` module. I have trained a voice up to script `06_train_acoustic_model` and am now trying to generate some wav files from text. I had no problem doing this in a previous attempt, but I had to start over in a different environment and now the process fails. 

Here are the scripts I'm calling on the python code to do the conversion:
Here are the scripts I'm calling to do the conversion in the python code:

```
    subprocess.check_call(speakeradaptation_path+'/scripts/prepare_labels_from_txt.sh %s %s %s' % (txt_dir, lab_dir, conf_file), shell=True)
    subprocess.check_call(speakeradaptation_path+'/scripts/submit.sh %s %s' % (merlin_path+'/src/run_merlin.py', dur_conf_file), shell=True)
    subprocess.check_call(speakeradaptation_path+'/scripts/submit.sh %s %s' % (merlin_path+'/src/run_merlin.py', synth_conf_file), shell=True)
    subprocess.check_call(speakeradaptation_path+'/scripts/remove_intermediate_files.sh %s' % (conf_file), shell=True)

```
And the actual error:
```
Traceback (most recent call last):
  File "/home/ajalali/merlin/src/run_merlin.py", line 1224, in <module>
    main_function(cfg)
  File "/home/ajalali/merlin/src/run_merlin.py", line 572, in main_function
    label_normaliser.perform_normalisation(in_label_align_file_list, binary_label_file_list, label_type=cfg.label_type)
  File "/home/ajalali/merlin/src/frontend/linguistic_base.py", line 68, in perform_normalisation
    self.extract_linguistic_features(ori_file_list[i], output_file_list[i], label_type)
  File "/home/ajalali/merlin/src/frontend/label_normalisation.py", line 26, in extract_linguistic_features
    A = self.load_labels_with_state_alignment(in_file_name)
  File "/home/ajalali/merlin/src/frontend/label_normalisation.py", line 496, in load_labels_with_state_alignment
    utt_labels = fid.readlines()
  File "/home/ajalali/merlin/.venv/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa4 in position 0: invalid start byte
```
The file in question is this:

`/home/ajalali/merlin/egs/speaker_adaptation/s1/experiments/demo/test_synthesis/gen-lab/Itsaverycommonidiomtoloadatemplatefillac.lab` (filename is part of the input text). 

Running `file -i` on it returns: 

`Itsaverycommonidiomtoloadatemplatefillac.lab: application/octet-stream; charset=binary`

So not a UTF-8 encoded file. 

I haven't changed any of the core code for speaker_adaptation or Merlin. 

Any ideas/suggestions on why this is happening and how to fix this?

**Comment by lomizandtyd** [comment]
It seems like that you use a binary label file generated by Merlin rather than a normal HTS label file.

I'm not familiar with speaker adaption. 
In TTS case, text lab files for test usually stay in "test/prompt-lab/".
