### ISSUE TITLE
train_dnn by tensorflow   ValueError: could not broadcast input array

### ISSUE THREAD

**Issue by haiewu** [CSTR-Edinburgh/merlin#380]
when I train dnn by tensorflow, I met the problem:
2018-07-11 14:29:54,704 CRITICAL       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/mnt/sdb1/whe/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/mnt/sdb1/whe/merlin/src/run_merlin.py", line 863, in main_function
    tf_instance.train_tensorflow_model()
  File "/mnt/sdb1/whe/merlin/src/run_tensorflow_with_merlin_io.py", line 177, in train_tensorflow_model
    self.inp_dim, self.out_dim, sequential_training=True if self.sequential_training or self.encoder_decoder else False)
  File "/mnt/sdb1/whe/merlin/src/tensorflow_lib/data_utils.py", line 92, in read_data_from_file_list
    temp_set_x[current_index:current_index+frame_number, ] = inp_features[0:frame_number]
ValueError: could not broadcast input array from shape (787,471) into shape (313,471)

**Comment by chazo1994** [comment]
I have same problems
