### ISSUE TITLE
AssertionError: check train, valid, test file number

### ISSUE THREAD

**Issue by yuuSiVo** [CSTR-Edinburgh/merlin#400]
Hi there! I got the error.
Here's a settings

train_file_number: 5
valid_file_number: 0
test_file_number: 5

I created only 5 wav files data

**Comment by seblemaguer** [comment]
if you have only 5 wav, you won't be able to train the models as they are requiring far much more data.

**Comment by yuuSiVo** [comment]
Thanks!! This issue is solved. But, I got new error 

2018-10-07 19:33:47,394 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1498 others 750
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/mnt/c/Users/admin/Downloads/merlin-master/src/run_merlin.py", line 487, in perform_acoustic_composition_on_split
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, in_dimension_dict, out_dimension_dict)
  File "/mnt/c/Users/admin/Downloads/merlin-master/src/frontend/acoustic_base.py", line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_dimension_dict)
  File "/mnt/c/Users/admin/Downloads/merlin-master/src/frontend/acoustic_composition.py", line 135, in prepare_data
    assert  out_frame_number == frame_number
AssertionError
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/c/Users/admin/Downloads/merlin-master/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/mnt/c/Users/admin/Downloads/merlin-master/src/run_merlin.py", line 692, in main_function
2018-10-07 19:33:47,714 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1636 others 819
    perform_acoustic_composition(delta_win, acc_win, in_file_list_dict, nn_cmp_file_list, cfg, parallel=True)
  File "/mnt/c/Users/admin/Downloads/merlin-master/src/run_merlin.py", line 510, in perform_acoustic_composition
    pool.map(perform_acoustic_composition_on_split, splits_full)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
AssertionError

I added 25 wav files

**Comment by ZackHodari** [comment]
Make sure to have your `file_id_list` contain a list of all files that you want available (for training, validation and testing). The sum of the values for `train_file_number`, `valid_file_number`, and `test_file_number` must be equal to the number of files in your `file_id_list`.

The problem you are seeing is due to the setup of the data and file lists, solve this first. Then, as Sebastien said, you will need more data to train a real model (you will need at least hundreds of files).
