### ISSUE TITLE
Problems with demos: No synthesized audio files for slt(bdl)_arctic_full, and others are crashing

### ISSUE THREAD

**Issue by gerazov** [CSTR-Edinburgh/merlin#403]
Thanks for sharing your work guys - it's awesome!

I've run into some problems running the demos. 
For both `slt_arctic_full` and `bdl_arctic_full` I get through all the bash scripts with no errors, but at the end of `./05_run_merlin.sh  slt(bdl)duration-conf slt(bdl)acoustic-conf` it says 
```
synthesized audio files are in: experiments/slt(bdl)_arctic_full/test_synthesis/wav
All successfull!! Your demo voice is ready :)
```
and there is nothing there - not even the folder is created.

On the other hand `slt_arctic_demo` finished without any errors and did output `.wav` files.  

Also, I had problems running the other databases:

- `awb_arctic_demo` -- I got up to `./03_train_duration_model.sh conf/duration_awb_arctic_demo.conf` and it crashed with:
```
Traceback (most recent call last):
  File "~/data/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "~/data/merlin/src/run_merlin.py", line 622, in main_function
    label_normaliser.perform_normalisation(in_label_align_file_list, binary_label_file_list, label_type=cfg.label_type)
  File "~/data/merlin/src/frontend/linguistic_base.py", line 74, in perform_normalisation
    pool.map(_perform_normalisation, range(self.utterance_num))
  File "~/miniconda3/envs/merlin/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "~/miniconda3/envs/merlin/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "~/miniconda3/envs/merlin/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "~/miniconda3/envs/merlin/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "~/data/merlin/src/frontend/linguistic_base.py", line 69, in _perform_normalisation
    self.extract_linguistic_features(ori_file_list[i], output_file_list[i], label_type)
  File "~/data/merlin/src/frontend/label_normalisation.py", line 26, in extract_linguistic_features
    A = self.load_labels_with_state_alignment(in_file_name)
  File "~/data/merlin/src/frontend/label_normalisation.py", line 484, in load_labels_with_state_alignment
    fid = open(file_name)
FileNotFoundError: [Errno 2] No such file or directory: '~/data/merlin/egs/slt_arctic/s1/experiments/awb_arctic_demo/duration_model/data/label_state_align/arctic_a0007.lab'
```
- `awb_arctic_full` --  I got up to `./03_train_duration_model.sh conf/duration_awb_arctic_full.conf` and it crashed with:
```
Traceback (most recent call last):
  File "~/data/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "~/data/merlin/src/run_merlin.py", line 551, in main_function
    assert cfg.train_file_number+cfg.valid_file_number+cfg.test_file_number == total_file_number, 'check train, valid, test file number'
AssertionError: check train, valid, test file number
```
It seems weird ...

**Comment by ZackHodari** [comment]
`awb_arctic_demo`: Have you tried tracking down if the file is missing (as per `FileNotFoundErrr`)? If so maybe the data was not downloaded correctly, or file_id_lists were incorrect?

`awb_arctic_full`: Could be the same cause as above. Or the file_id_lists don't agree with total_file_number.
