### ISSUE TITLE
assert  out_frame_number == frame_number error

### ISSUE THREAD

**Issue by shartoo** [CSTR-Edinburgh/merlin#421]
Here is the detail
```
2019-01-07 19:37:49,255 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1064 others 533
2019-01-07 19:37:49,330 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1040 others 521
2019-01-07 19:37:49,337 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1144 others 573
2019-01-07 19:37:49,350 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1164 others 583
2019-01-07 19:37:49,403 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1196 others 599
2019-01-07 19:37:49,424 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1236 others 619
2019-01-07 19:37:49,590 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1444 others 723
2019-01-07 19:37:49,918 CRITICAL  acoustic_comp: the frame number of data stream lf0 is not consistent with others: current 1760 others 881
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/deepblue/anaconda3/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/deepblue/anaconda3/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/home/deepblue/workspace/tts/merlin/src/run_merlin.py", line 487, in perform_acoustic_composition_on_split
    acoustic_worker.prepare_nn_data(in_file_list_dict, nn_cmp_file_list, in_dimension_dict, out_dimension_dict)
  File "/home/deepblue/workspace/tts/merlin/src/frontend/acoustic_base.py", line 122, in prepare_nn_data
    self.prepare_data(in_file_list_dict, out_file_list, in_dimension_dict, out_dimension_dict)
  File "/home/deepblue/workspace/tts/merlin/src/frontend/acoustic_composition.py", line 135, in prepare_data
    assert  out_frame_number == frame_number
AssertionError

```

My audio wav file are 48khz and mono,i have modified the sample rate value in `01_setup.sh`.

**Comment by RasmusD** [comment]
The error tells you exactly what is wrong.
I suggest you try figuring out why you have twice the number of frames for your lf0 extraction versus other features ;-)

**Comment by Roshan17** [comment]
Refer #90.
I also faced the same problem.(I used the script [](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.py) and later i found that number of frames in each of lf0, bap and mgc are not matching.) Later i used script [](https://github.com/CSTR-Edinburgh/merlin/blob/master/misc/scripts/vocoder/world/extract_features_for_merlin.sh) and it solved my problem.

**Comment by shartoo** [comment]
Hi @Roshan17  thank you for your advice ,but it did't work for me.The error still stay the same.

**Comment by shartoo** [comment]
This error may cause by my wrong version of anaconda ,i'm using anaconda3 with python 3.7 and it failed in step6 training a acoustic model.
