### ISSUE TITLE
Acoustic Model not converging.

### ISSUE THREAD

**Issue by anuragbanerjee2** [CSTR-Edinburgh/merlin#424]
I am using [LJSpeech](https://keithito.com/LJ-Speech-Dataset/). While the duration model converges, the acoustic model stops after some steps while using the DNN and BLSTM recipes. I am using the default question file and all default setting.

**Comment by yyf** [comment]
Were you able to train on the entire LJSpeech dataset? 

I was able to finish ./04_prepare_conf_files.sh, but got below error when running ./05_train_duration_model.sh: 


`
...
2019-03-04 18:32:47,333 INFO           main    :       D egs/slt_arctic/s2/run_demo.py
2019-03-04 18:32:47,333 INFO           main    :       D egs/slt_arctic/s2/scripts/__init__.py
2019-03-04 18:32:47,333 INFO           main    :       D egs/slt_arctic/s2/scripts/gpu_lock.py
2019-03-04 18:32:47,333 INFO           main    :       D egs/slt_arctic/s2/scripts/label_st_align_to_var_rate.py
2019-03-04 18:32:47,333 INFO           main    :       D egs/slt_arctic/s2/scripts/setup_env.sh
2019-03-04 18:32:47,333 INFO           main    :       D egs/slt_arctic/s2/scripts/submit.sh
2019-03-04 18:32:47,333 INFO           main    :       M misc/scripts/alignment/state_align/forced_alignment.py
2019-03-04 18:32:47,333 INFO           main    :       M tools/compile_other_speech_tools.sh
2019-03-04 18:32:47,334 INFO           main    :       (all diffs logged in feed_forward_6_tanh_06_32PM_March_04_2019.log.gitdiff)
2019-03-04 18:32:47,355 INFO           main    : Execution information:
2019-03-04 18:32:47,372 INFO           main    :   ...
2019-03-04 18:32:47,372 INFO           main    :   ...
2019-03-04 18:32:47,372 INFO           main    :   ...
Traceback (most recent call last):
  File "/home/.../merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/home/.../merlin/src/run_merlin.py", line 551, in main_function
    assert cfg.train_file_number+cfg.valid_file_number+cfg.test_file_number == total_file_number, 'check train, valid, test file number'
AssertionError: check train, valid, test file number`



I downsampled the 13100 files from the dataset to 16kHz, and set number of files in global_settings.cfg based on the suggestion in #203, i.e.
Train=11790
Valid=655
Test=655

Then, I check the number of files in the duration_model/data/file_id_list.scp, but there is only 2098 entries there. Is there additional config required to train on a larger dataset/the LJSpeech dataset? Also not sure why there are still slt_arctic related logs? 

Thanks.
