### ISSUE TITLE
IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by mrgloom** [CSTR-Edinburgh/merlin#442]
Get this error after runned `time ./run_full_voice.sh`:

```
2019-03-18 02:18:11,773 INFO    param_generation: processing    1 of    1: /data/user_data/external_projects/text-to-speech/merlin/egs/slt_arctic/s1/experiments/slt_arctic_full/test_synthesis/wav/test_me.cmp
Traceback (most recent call last):
  File "/data/user_data/external_projects/text-to-speech/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/data/user_data/external_projects/text-to-speech/merlin/src/run_merlin.py", line 971, in main_function
    generator.acoustic_decomposition(gen_file_list, cfg.cmp_dim, cfg.out_dimension_dict, cfg.file_extension_dict, var_file_dict, do_MLPG=cfg.do_MLPG, cfg=cfg)
  File "/data/user_data/external_projects/text-to-speech/merlin/src/frontend/parameter_generation.py", line 164, in acoustic_decomposition
    gen_features = mlpg_algo.generation(current_features, var, out_dimension_dict[feature_name]//3)
  File "/data/user_data/external_projects/text-to-speech/merlin/src/frontend/mlpg_fast.py", line 122, in generation
    var_frames[0, 1] = 100000000000;
IndexError: index 0 is out of bounds for axis 0 with size 0
Lock freed
deleting intermediate synthesis files...
synthesized audio files are in: experiments/slt_arctic_full/test_synthesis/wav
All successfull!! Your demo voice is ready :)

real	85m11.509s
user	525m7.484s
sys	404m31.404s
```

**Comment by ZackHodari** [comment]
It looks like `var_frames` is empty figuring out why may help solve the issue.

Following the trace it seems that this comes from [`features, frame_number = io_funcs.load_binary_file_frame(file_name, dimension)`](https://github.com/CSTR-Edinburgh/merlin/blob/master/src/frontend/parameter_generation.py#L144)

Try loading that file in a python prompt and see if it is empty or not.

**Comment by mrgloom** [comment]
Looks like the reason that on step 3 https://github.com/CSTR-Edinburgh/merlin/blob/9df27e9309edccb6e35511ead2e832f2fe98cc15/egs/slt_arctic/s1/run_full_voice.sh#L15 I was getting an error about the same as here:
https://github.com/CSTR-Edinburgh/merlin/issues/447
https://github.com/CSTR-Edinburgh/merlin/issues/414
https://github.com/CSTR-Edinburgh/merlin/issues/418

`ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)`

But processing don't stop, at step 4 I see that all CPU cores are 100% load, is it desired behaviour or does it mean that theano failed to run on GPU?

At which step `parameter_generation.py` is used?

**Comment by mrgloom** [comment]
`import theano` work without an error.

```
print(theano.__version__)
1.0.4
```

Looks like `pygpu` can be build like:
http://deeplearning.net/software/libgpuarray/installation.html#step-by-step-install

Running step 3 `./03_train_duration_model.sh conf/duration_slt_arctic_full.conf`

```
MERLIN_THEANO_FLAGS:
    cuda.root=/usr/local/8.0
    floatX=float32
    on_unused_input=ignore

Running on GPU id=1 ...
Can not use cuDNN on context None: cannot compile with cuDNN. We got this error:
b'In file included from /tmp/try_flags_hi2fruvy.c:4:0:\n/usr/include/cudnn.h:64:26: fatal error: cuda_runtime.h: No such file or directory\n #include <cuda_runtime.h>\n       $
Mapped name None to device cuda1: GeForce GTX TITAN X (0000:01:00.0)

Theano version: 1.0.4
THEANO_FLAGS: mode=FAST_RUN,device=cuda1,cuda.root=/usr/local/8.0,floatX=float32,on_unused_input=ignore
device: cuda1
```

**Comment by ZackHodari** [comment]
If pygpu fails, Theano will fall back to using the cpu and everything will work correctly, but may be slower.

`parameter_generation.py` is called in `run_merlin.py` when the config option `DNNGEN` is set to True and either `AcousticModel` or `DurationModel` is True.

You shouldn't need to install pygpu from scratch, try using conda or pip.

Did you try changing `MERLIN_THEANO_FLAGS`?

If you are still getting the `IndexError` something is probably breaking earlier, you'll need to figure out where based on why `var_frames` was empty.

**Comment by mrgloom** [comment]
The file that is not loaded in used on step 4 and have path is like `merlin/egs/slt_arctic/s1/experiments/slt_arctic_full/acoustic_model/gen/feed_forward_6_tanh/arctic_b0539.cmp`
Any ideas on which step and where in the code it should be generated?

**Comment by ZackHodari** [comment]
That is the composed (`.cmp`) predictions made by the model in `frontend.parameter_generation.ParameterGeneration` within `DNNGEN` of `run_merlin.py`.

You can check this is ran by this config from [line 123](https://github.com/CSTR-Edinburgh/merlin/blob/9df27e9309edccb6e35511ead2e832f2fe98cc15/egs/slt_arctic/s1/conf/dnn/acoustic_slt_arctic_full.conf#L123)

Try loading `arctic_b0539.cmp` using `io_funcs.binary_io.BinaryIOCollection` and see if it contains data.

**Comment by ZackHodari** [comment]
Unfortunately if something goes wrong earlier and no frames are produced, generation will "fail" silently and will save an empty array to a file.

Merlin's logging will give you information about when it fails, but it is hard to notice. In fact I just looked back at your original comment and noticed the following:

```
2019-03-18 02:22:23,190 INFO           labels  : loaded /data/user_data/external_projects/text-to-speech/merlin/egs/slt_arctic/s1/experiments/slt_arctic_full/test_synthesis/gen-lab/test_me.lab,   0 labels
```

It has `0 labels` this could be the root cause of the failure to synthesise anything.

**Comment by mirfan899** [comment]
I'm getting the same error. I tried many solutions but the problem still exists.

**Comment by mirfan899** [comment]
I found the solution related to my problem was, festival `utts.data` format was wrong. Adding proper format solved the issue.

**Comment by ratz-creator** [comment]
can you please specify the format
