### ISSUE TITLE
Error when synthesizing new speech

### ISSUE THREAD

**Issue by kevinmchu** [CSTR-Edinburgh/merlin#468]
I am trying to synthesize new test sentences using the full slt_arctic model, however I received the following error:

Traceback (most recent call last):
  File "/home/xxxxxx/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/home/xxxxxx/merlin/src/run_merlin.py", line 971, in main_function
    generator.acoustic_decomposition(gen_file_list, cfg.cmp_dim, cfg.out_dimension_dict, cfg.file_extension_dict, var_file_dict, do_MLPG=cfg.do_MLPG, cfg=cfg)
  File "/home/xxxxxx/merlin/src/frontend/parameter_generation.py", line 164, in acoustic_decomposition
    gen_features = mlpg_algo.generation(current_features, var, out_dimension_dict[feature_name]//3)
  File "/home/xxxxxx/merlin/src/frontend/mlpg_fast.py", line 122, in generation
    var_frames[0, 1] = 100000000000;
IndexError: index 0 is out of bounds for axis 0 with size 0
deleting intermediate synthesis files...
synthesized audio files are in: experiments/slt_arctic_full/test_synthesis/wav

What can I do to fix this problem?

**Comment by kevinmchu** [comment]
Found the problem. Some of my sentences were blank, which was causing the code to error. I replaced the blank sentences with dummy sentences and was able to get the code to run.
