### ISSUE TITLE
Error running Mandarin demo

### ISSUE THREAD

**Issue by mirfan899** [CSTR-Edinburgh/merlin#472]
I'm getting the following error when training the Mandarin synthesizer
```shell
2019-06-12 16:42:49,964 CRITICAL wav_generation: The vocoder world is not supported yet!

Traceback (most recent call last):
  File "/home/virtuoso_irfan/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/home/virtuoso_irfan/merlin/src/run_merlin.py", line 989, in main_function
    generate_wav(gen_dir, gen_file_id_list, cfg)     # generated speech
  File "/home/virtuoso_irfan/merlin/src/utils/generate.py", line 335, in generate_wav
    raise
RuntimeError: No active exception to reraise
```

**Comment by melspectrum007** [comment]
I run into the same problem "CRITICAL wav_generation: The vocoder world is not supported yet!", how do you solve it? could you give me some sugestion?

thanks a lot

**Comment by seblemaguer** [comment]
the vocoder type should be "WORLD" instead of "world"
