### ISSUE TITLE
CRITICALListDataProvider: the number of frames in label and acoustic features are different

### ISSUE THREAD

**Issue by priyanthini** [CSTR-Edinburgh/merlin#498]
I'm developing a TTS for Tamil usinng merlin. I have completed upto training duration model. Now error comes in 6th step, train_acoustic_model step.
Error comes as follows :

**2020-01-21 12:52:07,108 CRITICALListDataProvider: the number of frames in label and acoustic features are different: 533 vs 418 (ta_1436)
2020-01-21 12:52:07,121 CRITICAL       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/home/acc/merlin/src/run_merlin.py", line 1320, in <module>
    main_function(cfg)
  File "/home/acc/merlin/src/run_merlin.py", line 870, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector,init_dnn_model_file=cfg.start_from_trained_model)
  File "/home/acc/merlin/src/run_merlin.py", line 223, in train_DNN
    shared_train_set_xy, temp_train_set_x, temp_train_set_y = train_data_reader.load_one_partition()
  File "/home/acc/merlin/src/utils/providers.py", line 296, in load_one_partition
    shared_set_xy, temp_set_x, temp_set_y = self.load_next_partition()
  File "/home/acc/merlin/src/run_merlin.py", line 849, in main_function
    os.makedirs(model_dir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/acc/merlin/egs/build_your_own_voice/s2/experiments/my_voice/acoustic_model/nnets_model'**

How to solve this error???

**Comment by Aliraheem** [comment]
Hello, have you solved this issue? I have the same problem
