### ISSUE TITLE
python dependencies

### ISSUE THREAD

**Issue by nipppas** [CSTR-Edinburgh/merlin#500]
Hello I am trying to build merlin tts. Until now I have succesfully compiled all tools. 
When I install python dependencies such as:
pip install numpy scipy matplotlib lxml theano bandmat with python 2.7 its collecting and download each one of them but after that it gives that error:
ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-x_fijD/bandmat/setup.py'"'"'; __file__='"'"'/tmp/pip-install-x_fijD/bandmat/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-x_fijD/bandmat/pip-egg-info
         cwd: /tmp/pip-install-x_fijD/bandmat/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-x_fijD/bandmat/setup.py", line 10, in <module>
        import numpy as np
    ImportError: No module named numpy
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

if anyone knows it could be awesome

**Comment by seblemaguer** [comment]
are you sure that your pip is using the same python?

**Comment by nipppas** [comment]
It caused because of bandmat i have compiled without cuda so thats it!

**Comment by nipppas** [comment]
Yes and when I rerun it it compiled succesfully.. but when I went to egs/slt_arctic?s1 ./run_demo.sh
Step 1:
unzipping files......
[slt_arctic_demo_data.zip]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of slt_arctic_demo_data.zip or
        slt_arctic_demo_data.zip.zip, and cannot find slt_arctic_demo_data.zip.ZIP, period.
mv: cannot stat 'slt_arctic_demo_data/merlin_baseline_practice/duration_data/': No such file or directory
mv: cannot stat 'slt_arctic_demo_data/merlin_baseline_practice/acoustic_data/': No such file or directory
mv: cannot stat 'slt_arctic_demo_data/merlin_baseline_practice/test_data/': No such file or directory

**Comment by baniyacoder** [comment]
choose python2.7 -m pip install numpy i hope it works
