### ISSUE TITLE
unable to train the duration model

### ISSUE THREAD

**Issue by baniyacoder** [CSTR-Edinburgh/merlin#526]
I am using merlin in google colaboratory and i have installed python3.6 version as well as all the requirements and when i am training the duration model I am getting this error
Running on GPU id=0 ...
ERROR (theano.gpuarray): pygpu was configured but could not be imported or is too old (version 0.7 or higher required)
NoneType: None
/usr/local/lib/python3.7/dist-packages/theano/configparser.py:255: UserWarning: Theano does not recognise this flag: cuda.root
  warnings.warn(f"Theano does not recognise this flag: {key}")
Traceback (most recent call last):
  File "/content/merlin/src/run_merlin.py", line 65, in <module>
    from frontend.parameter_generation import ParameterGeneration
  File "/content/merlin/src/frontend/parameter_generation.py", line 50, in <module>
    from .mlpg_fast import MLParameterGenerationFast as MLParameterGeneration
  File "/content/merlin/src/frontend/mlpg_fast.py", line 53, in <module>
    import bandmat as bm
ModuleNotFoundError: No module named 'bandmat'
Lock freed

i have checked that i am unable to import bandmat in my google colaboratory

**Comment by baniyacoder** [comment]
what should i do???

**Comment by xyx361100238** [comment]
pip3 install  bandmat
