### ISSUE TITLE
I got the problem about 'full-context-labels/full/arctic_a0001.lab', can anyone help me?

### ISSUE THREAD

**Issue by fiantonumber1** [CSTR-Edinburgh/merlin#528]
Step 2: 
Preparing labels...
Making directories
Copying relevant script files
Generating clunits specific voice and build files
Set up for cmu_us_myownvoice complete
Copying general files
Copying intonation files
Copying duration files
Set up for cmu_us_myownvoice prosody complete
Generating additional clustergen specific voice and build files
Set up for cmu_us_myownvoice clustergen complete
Segmentation fault (core dumped)
EHMM setup
EHMM extract phone sequences and base hmm state numbers
Segmentation fault (core dumped)
Cannot open ehmm/etc/txt.phseq.data 
awk: fatal: cannot open file `ehmm/etc/txt.phseq.data' for reading (No such file or directory)
awk: fatal: cannot open file `ehmm/etc/txt.phseq.data' for reading (No such file or directory)
EHMM Feature extraction and normalization with new code
xargs: /content/merlin/tools/festvox/src/ehmm/bin/FeatureExtraction: No such file or directory
/content/merlin/tools/festvox/src/ehmm/bin/do_ehmm: 191: /content/merlin/tools/festvox/src/ehmm/bin/do_ehmm: /content/merlin/tools/festvox/src/ehmm/bin/ScaleBinaryFeats: not found
Cannot open ehmm/etc/ph_list 
EHMM baum-welch re-estimation
Using  threads
/content/merlin/tools/festvox/src/ehmm/bin/do_ehmm: 205: /content/merlin/tools/festvox/src/ehmm/bin/do_ehmm: /content/merlin/tools/festvox/src/ehmm/bin/ehmm: not found
EHMM align
/content/merlin/tools/festvox/src/ehmm/bin/do_ehmm: 217: /content/merlin/tools/festvox/src/ehmm/bin/do_ehmm: /content/merlin/tools/festvox/src/ehmm/bin/edec: not found
Cannot open ehmm/etc/ph_list.int 
Segmentation fault (core dumped)
awk: fatal: cannot open file `etc/silence' for reading (No such file or directory)
cat: ehmm/etc/ph_list.int_log: No such file or directory
EHMM standardize_statenames
mv: cannot stat 'lab/arctic_a0001.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0001.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0002.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0002.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0003.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0003.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0004.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0004.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0005.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0005.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0006.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0006.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0007.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0007.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0008.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0008.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0009.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0009.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0010.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0010.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0011.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0011.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0012.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0012.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0013.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0013.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0014.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0014.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0015.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0015.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0016.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0016.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0017.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0017.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0018.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0018.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0019.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0019.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0020.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0020.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0021.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0021.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0022.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0022.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0023.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0023.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0024.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0024.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0025.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0025.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0026.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0026.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0027.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0027.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0028.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0028.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0029.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0029.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0030.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0030.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0031.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0031.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0032.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0032.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0033.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0033.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0034.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0034.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0035.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0035.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0036.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0036.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0037.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0037.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0038.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0038.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0039.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0039.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0040.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0040.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0041.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0041.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0042.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0042.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0043.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0043.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0044.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0044.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0045.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0045.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0046.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0046.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0047.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0047.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0048.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0048.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0049.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0049.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0050.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0050.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0051.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0051.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0052.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0052.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0053.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0053.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0054.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0054.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0055.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0055.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0056.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0056.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0057.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0057.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0058.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0058.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0059.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0059.slehmm' for reading (No such file or directory)
mv: cannot stat 'lab/arctic_a0060.sl': No such file or directory
awk: etc/mapstatenames.awk:1: fatal: cannot open file `lab/arctic_a0060.slehmm' for reading (No such file or directory)
Segmentation fault (core dumped)
converting festival utts to labels...
cmu_us_myownvoice file_id_list.scp full-context-labels
gawk: fatal: cannot open file `full-context-labels/tmp' for reading (No such file or directory)
gawk: fatal: cannot open file `full-context-labels/tmp' for reading (No such file or directory)
normalizing label files for merlin...
arctic_a0001.lab
Traceback (most recent call last):
  File "/content/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 134, in <module>
    normalize_label_files(in_lab_file, out_lab_file, label_style, write_time_stamps)
  File "/content/merlin/misc/scripts/frontend/utils/normalize_lab_for_merlin.py", line 35, in normalize_label_files
    in_f = open(in_lab_file,'r')
FileNotFoundError: [Errno 2] No such file or directory: 'full-context-labels/full/arctic_a0001.lab'
Copying labels to duration and acoustic data directories...
done...!

**Comment by ADavis3333** [comment]
Hello, I have also encountered this problem. Have you solved it?
