### ISSUE TITLE
Check label- and features frame number mismatch before training

### ISSUE THREAD

**Issue by m-toman** [CSTR-Edinburgh/merlin#54]
Hi,

as I often stumble across the "CRITICAL^[[0mListDataProvider: the number of frames in label and acoustic features are different" errors, because of alignment issues, I wanted to add a check before the training.
I came up with this:

```
dir="$1"
    for f in $dir/label_state_align/*.lab
    do 
	fid=`basename $f .lab`
        ac_featnum=`$sptk_dir/x2x +fa $dir/lf0/${fid}.lf0 | wc -l`
	lab_endtime=`tail -n 1 $f | cut -d " " -f 2`
	lab_featnum=$((lab_endtime / 50000))
	feat_diff=$((lab_featnum - ac_featnum))

	if [ "$feat_diff" -lt "-5" ] || [ "$feat_diff" -gt "5" ]
	then
	    echo `date` "ERROR feature numbers for $fid differ ($lab_featnum - $ac_featnum = $feat_diff), sorting it out"
	    #rm -f $f
        fi
    done
```

Similar to what I found here: https://github.com/CSTR-Edinburgh/merlin/blob/master/src/utils/providers.py#L197
But it seems my results differ wildly from what happens later in merlin.

Do you have any hints for me to get this check right?
We could then probably integrate something like that into the build_your_own_voice shell scripts.

Thanks,
Markus

**Comment by ronanki** [comment]
The script looks okay to me -- I could successfully run this script on slt_arctic data without any errors.

**Comment by m-toman** [comment]
The interesting thing is, I get e.g.
"Thu Nov 24 11:39:44 UTC 2016 voice_train.sh: ERROR feature numbers for lab_201 differ (3890 - 3878 = 12), sorting it out"
and e.g.
"Thu Nov 24 11:39:44 UTC 2016 voice_train.sh: ERROR feature numbers for lab_236 differ (5326 - 5308 = 18), sorting it out"
(and a few others with high differences).

But the only label merlin complains later is:
"2016-11-24 11:47:55,799 ^[[1;35mCRITICAL^[[0mListDataProvider: the number of frames in label and acoustic features are different: 3880 vs 3873 (lab_201)
2016-11-24 11:47:55,799 ^[[1;35mCRITICAL^[[0m       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/home/ec2-user/voicesynthesis/DNN/merlin/src/run_merlin.py", line 1175, in <module>
    main_function(cfg)
  File "/home/ec2-user/voicesynthesis/DNN/merlin/src/run_merlin.py", line 838, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector)
  File "/home/ec2-user/voicesynthesis/DNN/merlin/src/run_merlin.py", line 277, in train_DNN
    shared_train_set_xy, temp_train_set_x, temp_train_set_y = train_data_reader.load_one_partition()
  File "/home/ec2-user/voicesynthesis/DNN/merlin/src/utils/providers.py", line 179, in load_one_partition
    shared_set_xy, temp_set_x, temp_set_y = self.load_next_partition()
  File "/home/ec2-user/voicesynthesis/DNN/merlin/src/utils/providers.py", line 330, in load_next_partition
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType
Lock freed"

Stating different frame numbers.
Is there any step in between that might modify the number of frames?

**Comment by ronanki** [comment]
This error is before training -- that means, silence is removed from both label and acoustic features. 

Check your alignments, whether end duration for last silence in label file is close to end point of the waveform or not?

**Comment by madhavivr** [comment]
I'm trying to build my own voice and I get the exact same error that m-toman posted. Can anyone tell me how to fix this problem.

**Comment by m-toman** [comment]
I threw out the samples that failed the check I postwd above and it works... but it seems to discard more samples than necessary.

When I calculate the duration without the silence from the labels, I get the same numbers as Merlin outputs. But the durations of the acoustic features are still different for me compared to the Merlin output

**Comment by madhavivr** [comment]
ok, thanks I will try that.

**Comment by xiaoyun4** [comment]
when I try to run the example of alt_arctic_demo,  all is right. But when I try to change the alt_arctic_data with my own data and the type of label is 'phone_label' ,     I get the exact same error:

Traceback (most recent call last):
  File "/home/xiaoyun/.virtualenvs/merlin/merlin-master/src/run_merlin.py", line 1172, in <module>
    main_function(cfg)
  File "/home/xiaoyun/.virtualenvs/merlin/merlin-master/src/run_merlin.py", line 835, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector)
  File "/home/xiaoyun/.virtualenvs/merlin/merlin-master/src/run_merlin.py", line 211, in train_DNN
    shared_train_set_xy, temp_train_set_x, temp_train_set_y = train_data_reader.load_one_partition()
  File "/home/xiaoyun/.virtualenvs/merlin/merlin-master/src/utils/providers.py", line 179, in load_one_partition
    shared_set_xy, temp_set_x, temp_set_y = self.load_next_partition()
  File "/home/xiaoyun/.virtualenvs/merlin/merlin-master/src/utils/providers.py", line 330, in load_next_partition
    raise
TypeError: exceptions must be old-style classes or derived from BaseException, not NoneType

And:

2017-06-21 16:06:24,144 [1;34mDEBUG   [0m main.train_DNN: Starting train_DNN
2017-06-21 16:06:24,144 [1;34mDEBUG   [0m main.train_DNN: Creating training   data provider
2017-06-21 16:06:24,144 [1;34mDEBUG   [0m main.train_DNN: Creating validation data provider
2017-06-21 16:06:24,144 [1;35mCRITICAL[0mListDataProvider: the number of frames in label and acoustic features are different: 181 vs 102 (nick_s1_0041)
2017-06-21 16:06:24,145 [1;35mCRITICAL[0m       main    : train_DNN threw an exception
Lock freed

the number of frames in label and acoustic features are different

Can anyone tell me how to fix this problem? Thanks

**Comment by madhavivr** [comment]
HI! The linguistic and acoustic features have different number of frames - did you check the obvious? If you did and your input linguistic features have the same number of frames as the acoustic features file, then the problem might be with the silence remove function - there is a variable for that in acoustic.conf file - set that to False and see if it works.
