### ISSUE TITLE
bug during training with new voice data

### ISSUE THREAD

**Issue by aniu** [CSTR-Edinburgh/merlin#69]
Hi, 
I replaced the slt_demo data with a new voice data, following the instruction given here. All the scripts for data prepreration went smoothly. However, during the  Step2 : training duration model, I got the following error info. Any idea or advice? Thanks a lot!

2017-01-02 00:34:49,253 DEBUG     acoustic_comp:  wrote 45 frames of features
2017-01-02 00:34:49,869 INFO           main    : normalising acoustic (output) features using method MVN
/home/merlin/src/frontend/mean_variance_norm.py:69: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if self.mean_vector == None:
/home/merlin/src/frontend/mean_variance_norm.py:71: FutureWarning: comparison to `None` will result in an elementwise object comparison in the future.
  if self.std_vector  == None:
2017-01-02 00:34:49,940 INFO           main    : saved MVN vectors to /home/merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/duration_model/data/norm_info_dur_5_MVN.dat
2017-01-02 00:34:49,941 INFO           main    : saved dur variance vector to /home//merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/duration_model/data/var/dur_5
2017-01-02 00:34:49,958 DEBUG          labels  : HTS-derived input feature dimension is 416 + 0 = 416
2017-01-02 00:34:49,958 INFO           main    : label dimension is 416
2017-01-02 00:34:49,959 INFO           main    : training DNN
2017-01-02 00:34:49,959 DEBUG    main.train_DNN: Starting train_DNN
2017-01-02 00:34:49,959 DEBUG    main.train_DNN: Creating training   data provider
2017-01-02 00:34:49,960 DEBUG    main.train_DNN: Creating validation data provider
2017-01-02 00:34:49,960 CRITICALListDataProvider: first list is empty
2017-01-02 00:34:49,960 CRITICAL       main    : train_DNN threw an exception
Traceback (most recent call last):
  File "/home//merlin/src/run_merlin.py", line 1175, in <module>
    main_function(cfg)
  File "/home/merlin/src/run_merlin.py", line 838, in main_function
    cmp_mean_vector = cmp_mean_vector, cmp_std_vector = cmp_std_vector)
  File "/home//merlin/src/run_merlin.py", line 209, in train_DNN
    n_ins = n_ins, n_outs = n_outs, buffer_size = buffer_size, sequential = sequential_training, shuffle = False)
  File "/home/merlin/src/utils/providers.py", line 88, in __init__
    assert len(x_file_list) > 0
AssertionError

**Comment by seblemaguer** [comment]
Hello,

apparently your validation list is empty which causes the error

**Comment by aniu** [comment]
In the demo, the validation file list  "test_id_list.scp" is specified in the test_data directory, right?

**Comment by ronanki** [comment]
test_id_list.scp is used only for test synthesis. 

Otherwise, file_id_list.scp is used and number of files for train, validation, test are used in config file.

**Comment by aniu** [comment]
yes. I actually followed the demo example, in the duration_slt_arctic_demo.conf, I specified the following
" [Data]
train_file_number: 417
valid_file_number: 5
test_file_number: 5"

note the total number of files in the new voice dataset is 417.  Very confused how the validation data became "empty"?  Any further advice for the bug ? I highly appreciate the effort :)

**Comment by ikhfa** [comment]
change the train_file_number to 407

**Comment by zhizhengwu** [comment]
(train_file_number + valid_file_number + test_file_number) should be
smaller than the total number of files.

**Comment by aniu** [comment]
Bug Solved!   Great thanks for the patient explanation and you guys are awesome !
