### ISSUE TITLE
basic issue with slt_arctic s1 demo

### ISSUE THREAD

**Issue by danieleghisi** [CSTR-Edinburgh/merlin#75]
Dear all, 

I'm very new to Merlin, and I'm sorry if this question is trivial. I just can't seem to be able to run the s1 demo properly. It stops at step 4 (synthesizing speech), because it can't find  "arctic_a0006.lab" in the prompt-lab directory. This directory only appears to contain files 1 through 5 and then 56 through 60.

Full log is here: data.danieleghisi.com/transfer/merlin_log.txt

What should I do? 
Thanks a lot in advance for any help!

PS. I am on Mac OS, I had to modify the "sed" commands in the configuration scripts to work properly (they need an explicit backup extension on Mac) but I don't think this is the issue.

**Comment by ronanki** [comment]
check your data/test_id_list.scp file -- make sure it has the list of files which are in prompt-lab directory only.

**Comment by danieleghisi** [comment]
Thanks for your quick answer.
Yes it does, it only has the ones which are in the prompt-lab directory. 
But it still doesn't work; from the log, it seems to load another scp file:

"Loaded file id list from /Users/danieleghisi/LibrariesAndStuff/merlin-master/egs/slt_arctic/s1/experiments/slt_arctic_demo/duration_model/data/file_id_list_demo.scp"

This other file has all the number 1 through 60...
Is there something else I can do?

Thanks,
d

**Comment by rowntreerob** [comment]
you might run 'setup' manually and verify the operations to unzip and to move the test data to proper destination.

./scripts/setup.sh slt_arctic_demo     //contains following:

if [[ ! -d ${data_dir} ]] || [[ -n "$do_unzip" ]]; then
    echo "unzipping files......"
    rm -fr ${data_dir}
    rm -fr ${duration_dir}/data
    rm -fr ${acoustic_dir}/data
    unzip -q ${data_dir}.zip
    mv ${data_dir}/merlin_baseline_practice/duration_data/ ${duration_dir}/data
    mv ${data_dir}/merlin_baseline_practice/acoustic_data/ ${acoustic_dir}/data
    mv ${data_dir}/merlin_baseline_practice/test_data/ ${synthesis_dir}

**Comment by ronanki** [comment]
Probably, you haven't created test synthesis configuration files. Make sure, you are using right set of configuration files. 

There should be four configuration files as shown in below path:
https://github.com/CSTR-Edinburgh/merlin/tree/master/egs/slt_arctic/s1/conf/dnn

When you are synthesizing, make sure you have test_*.conf files and GenTestList set to True in each of those files. Compare with below file:
https://github.com/CSTR-Edinburgh/merlin/blob/master/egs/slt_arctic/s1/conf/dnn/test_dur_synth_slt_arctic_full.conf

**Comment by maelp** [comment]
I have the same issue, there seems to be an inconsistency where the script looks for `.lab` files which do not exist in the directory

When using `run_full_voice` I get this error at the synthesis step

```
Traceback (most recent call last):
  File "/Users/primet/tmp/speech/merlin/src/run_merlin.py", line 1177, in <module>
    main_function(cfg)
  File "/Users/primet/tmp/speech/merlin/src/run_merlin.py", line 556, in main_function
    label_normaliser.perform_normalisation(in_label_align_file_list, binary_label_file_list, label_type=cfg.label_type)
  File "/Users/primet/tmp/speech/merlin/src/frontend/linguistic_base.py", line 68, in perform_normalisation
    self.extract_linguistic_features(ori_file_list[i], output_file_list[i], label_type)
  File "/Users/primet/tmp/speech/merlin/src/frontend/label_normalisation.py", line 31, in extract_linguistic_features
    A = self.load_labels_with_state_alignment(in_file_name)
  File "/Users/primet/tmp/speech/merlin/src/frontend/label_normalisation.py", line 426, in load_labels_with_state_alignment
    fid = open(file_name)
IOError: [Errno 2] No such file or directory: '/Users/primet/tmp/speech/merlin/egs/slt_arctic/s1/experiments/slt_arctic_full/test_synthesis/gen-lab/arctic_a0001.lab'
```

there is only a `prompt-lab` and not a `gen-lab` directory in `slt_arctic_full/test_synthesis`

When using `run_demo.sh` I get this error at the synthesis step:

```
2017-02-17 13:13:57,635 INFO           labels  : loaded /Users/primet/tmp/speech/merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/test_synthesis/prompt-lab/arctic_a0005.lab,  85 labels
2017-02-17 13:13:57,659 DEBUG          labels  : made label matrix of 17 frames x 416 labels
Traceback (most recent call last):
  File "/Users/primet/tmp/speech/merlin/src/run_merlin.py", line 1177, in <module>
    main_function(cfg)
  File "/Users/primet/tmp/speech/merlin/src/run_merlin.py", line 556, in main_function
    label_normaliser.perform_normalisation(in_label_align_file_list, binary_label_file_list, label_type=cfg.label_type)
  File "/Users/primet/tmp/speech/merlin/src/frontend/linguistic_base.py", line 68, in perform_normalisation
    self.extract_linguistic_features(ori_file_list[i], output_file_list[i], label_type)
  File "/Users/primet/tmp/speech/merlin/src/frontend/label_normalisation.py", line 31, in extract_linguistic_features
    A = self.load_labels_with_state_alignment(in_file_name)
  File "/Users/primet/tmp/speech/merlin/src/frontend/label_normalisation.py", line 426, in load_labels_with_state_alignment
    fid = open(file_name)
IOError: [Errno 2] No such file or directory: '/Users/primet/tmp/speech/merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/test_synthesis/prompt-lab/arctic_a0006.lab'
```

The `slt_arctic_demo/test_synthesis/prompt-lab` contains a few files, but not all of them (and not `arctic_a0006.lab`):

```
$ ls experiments/slt_arctic_demo/test_synthesis/prompt-lab
arctic_a0001.lab arctic_a0004.lab arctic_a0057.lab arctic_a0060.lab
arctic_a0002.lab arctic_a0005.lab arctic_a0058.lab
arctic_a0003.lab arctic_a0056.lab arctic_a0059.lab
```

```
$ cat experiments/slt_arctic_demo/test_synthesis/test_id_list.scp
arctic_a0001
arctic_a0002
arctic_a0003
arctic_a0004
arctic_a0005
arctic_a0056
arctic_a0057
arctic_a0058
arctic_a0059
arctic_a0060
```

**Comment by maelp** [comment]
@ronanki I have all four (actually 8: 4 for `demo` and 4 for `full_voice`) configuration files, they seem to refer to the proper files

The `test_*.conf` files did NOT have `GenTestList: True` (they were set to False). I updated the files and tried rerunning only the 4th (synthesis) step in the script but there was the same error, I will try rerunning the entire script with the learning to see

**Comment by maelp** [comment]
Update: after modifying the `test_*.conf` files to add `GenTestList: True` and rerunning the complete `run_demo` training script, it seems to load the correct list of files, but I now get this error at the synthesis step:

```
/merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/test_synthesis/prompt-lab/arctic_a0060.lab, 110 labels
2017-02-17 13:38:35,163 DEBUG          labels  : made label matrix of 22 frames x 416 labels
2017-02-17 13:38:35,181 DEBUG     acoustic_norm: MinMaxNormalisation created for feature dimension of 416
2017-02-17 13:38:35,181 INFO      acoustic_norm: Loaded min max values from the trained data for feature dimension of 416
2017-02-17 13:38:35,189 INFO           main    : creating duration (output) features
the number of input and output files should be the same!
```

**Comment by maelp** [comment]
After more tinkering, it seems the problem comes from the configuration script on osX, because the version of `sed` on osX is not compatible with GNU `sed`, and in particular: `-i` requires an extension (eg `-i.bak`) and the regular expressions like `GenTestList\s*:.*` are not correctly parsed (the `\s*` seems to not parse)

The best option is to `brew install gsed` (GNU sed) and to replace all the `sed -i ...` commands by `gsed -i ...`

We could make the scripts osX-compatible by defining something like:

```
$SED=sed # assumes GNU sed
if [[ "$OSTYPE" == "darwin"* ]]; then
    $SED=gsed
fi

...

$SED -i s/.../.../ $file

```
