### ISSUE TITLE
"Step 4: synthesizing speech..." crashing in SLT's run_demo.sh

### ISSUE THREAD

**Issue by gillesdegottex** [CSTR-Edinburgh/merlin#82]
test_synthesis/test_id_list.scp is called by it has never been created.
it seems only ./merlin_synthesis.sh creates it currently.

**Comment by gillesdegottex** [comment]
Maybe run_demo.sh should not use GenTest, but just generate the waveform of the test and validation set ?

**Comment by maelp** [comment]
I have the same issue, there seems to be an inconsistency where the script looks for `.lab` files which do not exist in the directory

When using `run_full_voice` I get this error at the synthesis step

```
Traceback (most recent call last):
  File "/Users/primet/tmp/speech/merlin/src/run_merlin.py", line 1177, in <module>
    main_function(cfg)
  File "/Users/primet/tmp/speech/merlin/src/run_merlin.py", line 556, in main_function
    label_normaliser.perform_normalisation(in_label_align_file_list, binary_label_file_list, label_type=cfg.label_type)
  File "/Users/primet/tmp/speech/merlin/src/frontend/linguistic_base.py", line 68, in perform_normalisation
    self.extract_linguistic_features(ori_file_list[i], output_file_list[i], label_type)
  File "/Users/primet/tmp/speech/merlin/src/frontend/label_normalisation.py", line 31, in extract_linguistic_features
    A = self.load_labels_with_state_alignment(in_file_name)
  File "/Users/primet/tmp/speech/merlin/src/frontend/label_normalisation.py", line 426, in load_labels_with_state_alignment
    fid = open(file_name)
IOError: [Errno 2] No such file or directory: '/Users/primet/tmp/speech/merlin/egs/slt_arctic/s1/experiments/slt_arctic_full/test_synthesis/gen-lab/arctic_a0001.lab'
```

there is only a `prompt-lab` directory in `slt_arctic_full/test_synthesis`

When using `run_demo.sh` I get this error at the synthesis step:

```
2017-02-17 13:13:57,635 INFO           labels  : loaded /Users/primet/tmp/speech/merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/test_synthesis/prompt-lab/arctic_a0005.lab,  85 labels
2017-02-17 13:13:57,659 DEBUG          labels  : made label matrix of 17 frames x 416 labels
Traceback (most recent call last):
  File "/Users/primet/tmp/speech/merlin/src/run_merlin.py", line 1177, in <module>
    main_function(cfg)
  File "/Users/primet/tmp/speech/merlin/src/run_merlin.py", line 556, in main_function
    label_normaliser.perform_normalisation(in_label_align_file_list, binary_label_file_list, label_type=cfg.label_type)
  File "/Users/primet/tmp/speech/merlin/src/frontend/linguistic_base.py", line 68, in perform_normalisation
    self.extract_linguistic_features(ori_file_list[i], output_file_list[i], label_type)
  File "/Users/primet/tmp/speech/merlin/src/frontend/label_normalisation.py", line 31, in extract_linguistic_features
    A = self.load_labels_with_state_alignment(in_file_name)
  File "/Users/primet/tmp/speech/merlin/src/frontend/label_normalisation.py", line 426, in load_labels_with_state_alignment
    fid = open(file_name)
IOError: [Errno 2] No such file or directory: '/Users/primet/tmp/speech/merlin/egs/slt_arctic/s1/experiments/slt_arctic_demo/test_synthesis/prompt-lab/arctic_a0006.lab'
```

The `slt_arctic_demo/test_synthesis/prompt-lab` contains a few files, but not all of them (and not `arctic_a0006.lab`):

```
$ ls slt_arctic_demo/test_synthesis/prompt-lab
arctic_a0001.lab arctic_a0004.lab arctic_a0057.lab arctic_a0060.lab
arctic_a0002.lab arctic_a0005.lab arctic_a0058.lab
arctic_a0003.lab arctic_a0056.lab arctic_a0059.lab
```

**Comment by ronanki** [comment]
test_id_list.scp is provided along with other test files. Therefore, there is no problem in running the demo. 

./merlin_synthesis.sh is used only for synthesizing new text.
